# 데이터 가져오기

## 독립변수

In [1]:
import requests
import pandas as pd
import urllib3

# SSL 경고 메시지 숨기기
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# API 키 입력
API_KEY = "5STQAATD94Z76TI7W683"

# ECOS open API로 데이터 가져오기
def get_ecos_data(stat_code, cycle, start_date, end_date, item_code, col_name):
    url = (
        f"https://ecos.bok.or.kr/api/StatisticSearch/"
        f"{API_KEY}/json/kr/1/3000/"                                   # 1~3000번째 데이터: 주말, 공휴일 제외 10년치 약 3000개
        f"{stat_code}/{cycle}/{start_date}/{end_date}/{item_code}"     # 통계표 코드/주기(D:일별, M:월별)/시작일/종료일/항목 코드
    )
    # 요청 보내기
    response = requests.get(url, verify=False)
    data = response.json()

    # 데이터 파싱
    rows = data["StatisticSearch"]["row"]
    df = pd.DataFrame(rows)

    # 필요한 컬럼만 정리
    df = df[["TIME", "DATA_VALUE"]].rename(columns={
        "TIME": "날짜",
        "DATA_VALUE": col_name
    })

    df[col_name] = pd.to_numeric(df[col_name])  # 숫자 타입으로 변환

    return df

1. 원/달러 환율, 한국 기준금리

In [2]:
ex_rate = get_ecos_data("731Y001", "D", "20190101", "20241231", "0000001", "원/달러환율")
kr_rate = get_ecos_data("722Y001", "M", "201901", "202412", "0101000", "한국금리")

print(ex_rate.shape)
print(ex_rate.head(10))

(1483, 2)
         날짜  원/달러환율
0  20190102  1118.1
1  20190103  1119.0
2  20190104  1127.5
3  20190107  1125.2
4  20190108  1118.0
5  20190109  1121.7
6  20190110  1121.6
7  20190111  1118.9
8  20190114  1117.6
9  20190115  1121.4

In [3]:
print(kr_rate.shape)
print(kr_rate.head(10))

(72, 2)
       날짜  한국금리
0  201901  1.75
1  201902  1.75
2  201903  1.75
3  201904  1.75
4  201905  1.75
5  201906  1.75
6  201907  1.50
7  201908  1.50
8  201909  1.50
9  201910  1.25

2. 미국연방기금금리(FFR)
- 단위: %

In [4]:
us_rate = pd.read_csv("./data/FEDFUNDS.csv")

print(us_rate.shape)
print(us_rate.head(10))

(72, 2)
  observation_date  FEDFUNDS
0       2019-01-01      2.40
1       2019-02-01      2.40
2       2019-03-01      2.41
3       2019-04-01      2.42
4       2019-05-01      2.39
5       2019-06-01      2.38
6       2019-07-01      2.40
7       2019-08-01      2.13
8       2019-09-01      2.04
9       2019-10-01      1.83

In [5]:
us_rate.columns = ['날짜', '미국금리']
us_rate.head(3)

           날짜  미국금리
0  2019-01-01  2.40
1  2019-02-01  2.40
2  2019-03-01  2.41

3. 유가

In [6]:
oil_price = pd.read_csv("./data/국제_원유가격20190101-20241231.csv")

oil_price = oil_price.rename(columns={"기간": "날짜"})

#wti   = oil_price[["날짜", "WTI"]].copy()
dubai = oil_price[["날짜", "Dubai"]].copy()

# print(wti.head(3))
print(dubai.head(3))

          날짜  Dubai
0  19년01월02일  51.86
1  19년01월03일  53.20
2  19년01월04일  55.59

## 종속변수

1. 품목별 국가별 수출입 실적

In [63]:
import glob

# 폴더 경로 지정
folder = r"C:\Users\926174\Downloads\수출입 실적"

files = glob.glob(folder + r"\수출입 실적(품목별+국가별)_*.csv")

trade_list = []
for file in sorted(files):
    df = pd.read_csv(file, encoding='utf-8-sig')
    trade_list.append(df)
    print(f"{file} 로드 완료 → {df.shape}")

# 하나로 합치기
trade = pd.concat(trade_list, ignore_index=True)

# 총계 행 제거
trade = trade[trade['기간'] != '총계'].reset_index(drop=True)

print(f"\n최종 shape: {trade.shape}")
trade.head(5)

C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_2015.csv 로드 완료 → (95804, 9)
C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_2016.csv 로드 완료 → (96814, 9)
C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_2017.csv 로드 완료 → (97724, 9)
C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_2018.csv 로드 완료 → (99286, 9)
C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_201901_11.csv 로드 완료 → (92203, 9)
C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_201912.csv 로드 완료 → (8458, 9)
C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_2020.csv 로드 완료 → (99617, 9)
C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_202101_11.csv 로드 완료 → (93486, 9)
C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_202112.csv 로드 완료 → (8593, 9)
C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_202201_11.csv 로드 완료 → (92691, 9)
C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_202212.csv 로드 완료 → (8477, 9)
C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_202301_11.csv 로드 완료 → (93452, 9)
C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_202312.csv 로드 완료 → (8519, 9)
C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_202401_11.csv 로드 완료 → (94153, 9)
C:\Users\926174\Downloads\수출입 실적\수출입 실적(품목별+국가별)_202412.csv 로드 완료 → (8768, 9)

최종 shape: (998030, 9)

,기간,국가,HS코드,품목명,수출 중량,수출 금액,수입 중량,수입 금액,무역수지
0,2015-01,가나,3.0,어류ㆍ갑각류ㆍ연체동물과 그 밖의 수생(水生) 무척추동물,81.0,120,0.0,0,120
1,2015-01,가나,12.0,"채유(採油)에 적합한 종자와 과실, 각종 종자와 과실, 공업용ㆍ의약용 식물, 짚과 ...",0.0,2,0.0,0,2
2,2015-01,가나,15.0,"동물성ㆍ식물성ㆍ미생물성 지방과 기름 및이들의 분해생산물, 조제한 식용 지방과 동물성...",0.0,0,17.5,56,-56
3,2015-01,가나,17.0,당류(糖類)와 설탕과자,1.5,33,0.0,0,33
4,2015-01,가나,18.0,코코아와 그 조제품,0.8,28,1223.8,1980,-1952

In [10]:
import requests
import pandas as pd
import xml.etree.ElementTree as ET
import time

# ================================================
# STEP 1. 기본 설정
# ================================================

API_KEY = "d14e288e04bef1da401d66602694b68e03f685e96b078e003b3091eeb8bb8210"   # ← Decoding 키 입력

START_YEAR  = 2019
END_YEAR    = 2024
OUTPUT_FILE = "trade_data_final.csv"
API_URL     = "http://apis.data.go.kr/1220000/nitemtrade/getNitemtradeList"


# ================================================
# STEP 2. 수집할 HS코드 50개
# ================================================

HS_CODES = {
    # --- 환율 민감 (15개) ---
    "854231": ("반도체_메모리",       "환율"),
    "854232": ("반도체_비메모리",     "환율"),
    "854239": ("기타집적회로",        "환율"),
    "851762": ("통신기기부품",        "환율"),
    "851769": ("기타통신기기",        "환율"),
    "852872": ("평판디스플레이",      "환율"),
    "870321": ("승용차_1000cc이하",   "환율"),
    "870322": ("승용차_1000~1500cc", "환율"),
    "870323": ("승용차_1500~3000cc", "환율"),
    "870324": ("승용차_3000cc초과",   "환율"),
    "870840": ("자동차변속기",        "환율"),
    "870850": ("자동차구동축",        "환율"),
    "870899": ("기타자동차부품",      "환율"),
    "901380": ("광학기기",            "환율"),
    "903289": ("계측제어기기",        "환율"),
    # --- 유가 민감 (15개) ---
    "271012": ("경유등유",            "유가"),
    "271019": ("기타석유제품",        "유가"),
    "271111": ("LPG액화",             "유가"),
    "271121": ("LNG액화",             "유가"),
    "290110": ("에틸렌",              "유가"),
    "290121": ("에틸렌기타",          "유가"),
    "290129": ("기타기초유분",        "유가"),
    "390110": ("폴리에틸렌저밀도",    "유가"),
    "390120": ("폴리에틸렌고밀도",    "유가"),
    "390210": ("폴리프로필렌",        "유가"),
    "390410": ("PVC",                 "유가"),
    "390760": ("PET",                 "유가"),
    "330499": ("화장품기타",          "유가"),
    "320419": ("합성염료",            "유가"),
    "381400": ("혼합용제희석제",      "유가"),
    # --- 금리 민감 (10개) ---
    "847989": ("일반기계기타",        "금리"),
    "847950": ("산업용로봇",          "금리"),
    "842951": ("불도저굴착기",        "금리"),
    "842952": ("스크레이퍼",          "금리"),
    "890190": ("선박기타",            "금리"),
    "890120": ("탱커",                "금리"),
    "890130": ("냉동선",              "금리"),
    "720826": ("열연강판",            "금리"),
    "720839": ("냉연강판",            "금리"),
    "730511": ("강관",                "금리"),
    # --- 복합 충격 (10개) ---
    "850760": ("리튬이온이차전지",    "복합"),
    "850780": ("기타이차전지",        "복합"),
    "848620": ("반도체제조장비",      "복합"),
    "848630": ("반도체공정장비",      "복합"),
    "300490": ("의약품기타",          "복합"),
    "300420": ("항생제",              "복합"),
    "880240": ("항공기",              "복합"),
    "880330": ("항공기부품",          "복합"),
    "854140": ("태양전지",            "복합"),
    "902780": ("분석기기",            "복합"),
}


# ================================================
# STEP 3. 수출 대상국 25개
# ================================================

COUNTRIES = {
    "US": "미국",       "CN": "중국",       "VN": "베트남",
    "HK": "홍콩",       "JP": "일본",       "TW": "대만",
    "IN": "인도",       "SG": "싱가포르",   "MY": "말레이시아",
    "AU": "호주",       "DE": "독일",       "NL": "네덜란드",
    "GB": "영국",       "PL": "폴란드",     "IT": "이탈리아",
    "SA": "사우디",     "AE": "UAE",        "MX": "멕시코",
    "CA": "캐나다",     "BR": "브라질",     "TH": "태국",
    "ID": "인도네시아", "PH": "필리핀",     "BD": "방글라데시",
    "RU": "러시아",
}


# ================================================
# STEP 4. API 호출 함수 (XML 파싱)
# ================================================

def get_one(hs_code, country_code, year):
    """
    XML 응답을 받아서 파싱하는 함수
    """

    params = {
        "serviceKey": API_KEY,
        "strtYymm":   f"{year}01",
        "endYymm":    f"{year}12",
        "hsSgn":      hs_code,
        "cntyCd":     country_code,
    }

    try:
        resp = requests.get(API_URL, params=params, timeout=15)
        resp.raise_for_status()

        # XML 파싱
        root  = ET.fromstring(resp.text)
        items = root.findall(".//item")

        result = []
        for item in items:
            year_val = item.findtext("year", "")

            # "총계" 행 제거
            if year_val == "총계":
                continue

            result.append({
                "year":        year_val,
                "expDlr":      item.findtext("expDlr",      "0"),
                "expWgt":      item.findtext("expWgt",      "0"),
                "impDlr":      item.findtext("impDlr",      "0"),
                "impWgt":      item.findtext("impWgt",      "0"),
                "balPayments": item.findtext("balPayments", "0"),
            })

        return result

    except ET.ParseError as e:
        # XML 파싱 실패 시 응답 내용 출력 (디버깅용)
        print(f"\n  ⚠️  XML 파싱 오류 [{hs_code}][{country_code}] {year}년")
        print(f"      응답 내용 (앞 200자): {resp.text[:200]}")
        return []

    except Exception as e:
        print(f"\n  ⚠️  오류 [{hs_code}][{country_code}] {year}년: {e}")
        return []


# ================================================
# STEP 5. 전체 수집
# ================================================

def collect():

    result = []
    total  = len(HS_CODES) * len(COUNTRIES) * (END_YEAR - START_YEAR + 1)
    count  = 0

    for hs_code, (hs_name, shock_type) in HS_CODES.items():
        print(f"\n▶ [{hs_code}] {hs_name} ({shock_type})")

        for country_code, country_name in COUNTRIES.items():
            for year in range(START_YEAR, END_YEAR + 1):

                count += 1
                print(f"  {country_name}({country_code}) {year}년 ({count}/{total})", end=" ")

                items = get_one(hs_code, country_code, year)

                for item in items:
                    year_month = item["year"].replace(".", "-")  # "2019.01" → "2019-01"

                    result.append({
                        "연월":     year_month,
                        "연도":     year_month[:4],
                        "월":       year_month[5:7],
                        "HS코드":   hs_code,
                        "품목명":   hs_name,
                        "충격유형": shock_type,
                        "국가코드": country_code,
                        "국가명":   country_name,
                        "수출금액": item["expDlr"],
                        "수출중량": item["expWgt"],
                        "수입금액": item["impDlr"],
                        "수입중량": item["impWgt"],
                        "무역수지": item["balPayments"],
                    })

                print(f"→ {len(items)}건")
                time.sleep(0.2)

    return result


# ================================================
# STEP 6. 저장
# ================================================

def save(result):

    df = pd.DataFrame(result)

    for col in ["수출금액", "수출중량", "수입금액", "수입중량", "무역수지"]:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

    df["날짜"] = pd.to_datetime(df["연월"], format="%Y-%m", errors="coerce")
    df = df.sort_values(["충격유형", "HS코드", "국가코드", "날짜"]).reset_index(drop=True)
    df.to_csv(OUTPUT_FILE, index=False, encoding="utf-8-sig")

    print(f"\n{'='*55}")
    print(f"✅ 저장 완료: {OUTPUT_FILE}")
    print(f"   총 행수:  {len(df):,}행")
    print(f"   기간:     {df['연월'].min()} ~ {df['연월'].max()}")
    print(f"\n▶ 충격유형별 행수:")
    print(df.groupby("충격유형")["연월"].count().to_string())
    print(f"\n▶ 미리보기 (상위 5행):")
    print(df.head().to_string(index=False))

    return df


# ================================================
# 실행
# ================================================

if __name__ == "__main__":

    total_calls = len(HS_CODES) * len(COUNTRIES) * (END_YEAR - START_YEAR + 1)

    print("=" * 55)
    print("관세청 수출입 데이터 수집")
    print(f"HS코드:  {len(HS_CODES)}개")
    print(f"국가:    {len(COUNTRIES)}개국")
    print(f"기간:    {START_YEAR}년 ~ {END_YEAR}년")
    print(f"총 호출: {total_calls:,}번 (트래픽 {total_calls/10000*100:.0f}% 사용)")
    print("=" * 55)

    result = collect()

    if result:
        df = save(result)
    else:
        print("⚠️ 수집된 데이터가 없습니다. API 키와 파라미터를 확인하세요.")

=======================================================
관세청 수출입 데이터 수집
HS코드:  50개
국가:    25개국
기간:    2019년 ~ 2024년
총 호출: 7,500번 (트래픽 75% 사용)
=======================================================

▶ [854231] 반도체_메모리 (환율)
  미국(US) 2019년 (1/7500) → 78건
  미국(US) 2020년 (2/7500) → 73건
  미국(US) 2021년 (3/7500) → 74건
  미국(US) 2022년 (4/7500) → 48건
  미국(US) 2023년 (5/7500) → 48건
  미국(US) 2024년 (6/7500) → 48건
  중국(CN) 2019년 (7/7500) → 88건
  중국(CN) 2020년 (8/7500) → 89건
  중국(CN) 2021년 (9/7500) → 90건
  중국(CN) 2022년 (10/7500) → 50건
  중국(CN) 2023년 (11/7500) → 48건
  중국(CN) 2024년 (12/7500) → 48건
  베트남(VN) 2019년 (13/7500) → 63건
  베트남(VN) 2020년 (14/7500) → 78건
  베트남(VN) 2021년 (15/7500) → 67건
  베트남(VN) 2022년 (16/7500) → 43건
  베트남(VN) 2023년 (17/7500) → 39건
  베트남(VN) 2024년 (18/7500) → 45건
  홍콩(HK) 2019년 (19/7500) → 76건
  홍콩(HK) 2020년 (20/7500) → 75건
  홍콩(HK) 2021년 (21/7500) → 74건
  홍콩(HK) 2022년 (22/7500) → 48건
  홍콩(HK) 2023년 (23/7500) → 48건
  홍콩(HK) 2024년 (24/7500) → 48건
  일본(JP) 2019년 (25/7500) → 66건
  일본(JP) 2020년 (26/7500) → 63건
  일본(JP) 2021년 (27/7500) → 66건
  일본(JP) 2022년 (28/7500) → 48건
  일본(JP) 2023년 (29/7500) → 48건
  일본(JP) 2024년 (30/7500) → 48건
  대만(TW) 2019년 (31/7500) → 77건
  대만(TW) 2020년 (32/7500) → 88건
  대만(TW) 2021년 (33/7500) → 86건
  대만(TW) 2022년 (34/7500) → 48건
  대만(TW) 2023년 (35/7500) → 48건
  대만(TW) 2024년 (36/7500) → 48건
  인도(IN) 2019년 (37/7500) → 51건
  인도(IN) 2020년 (38/7500) → 47건
  인도(IN) 2021년 (39/7500) → 57건
  인도(IN) 2022년 (40/7500) → 39건
  인도(IN) 2023년 (41/7500) → 36건
  인도(IN) 2024년 (42/7500) → 39건
  싱가포르(SG) 2019년 (43/7500) → 57건
  싱가포르(SG) 2020년 (44/7500) → 60건
  싱가포르(SG) 2021년 (45/7500) → 68건
  싱가포르(SG) 2022년 (46/7500) → 41건
  싱가포르(SG) 2023년 (47/7500) → 45건
  싱가포르(SG) 2024년 (48/7500) → 47건
  말레이시아(MY) 2019년 (49/7500) → 57건
  말레이시아(MY) 2020년 (50/7500) → 69건
  말레이시아(MY) 2021년 (51/7500) → 76건
  말레이시아(MY) 2022년 (52/7500) → 48건
  말레이시아(MY) 2023년 (53/7500) → 48건
  말레이시아(MY) 2024년 (54/7500) → 46건
  호주(AU) 2019년 (55/7500) → 16건
  호주(AU) 2020년 (56/7500) → 14건
  호주(AU) 2021년 (57/7500) → 16건
  호주(AU) 2022년 (58/7500) → 15건
  호주(AU) 2023년 (59/7500) → 13건
  호주(AU) 2024년 (60/7500) → 16건
  독일(DE) 2019년 (61/7500) → 60건
  독일(DE) 2020년 (62/7500) → 61건
  독일(DE) 2021년 (63/7500) → 72건
  독일(DE) 2022년 (64/7500) → 47건
  독일(DE) 2023년 (65/7500) → 48건
  독일(DE) 2024년 (66/7500) → 48건
  네덜란드(NL) 2019년 (67/7500) → 33건
  네덜란드(NL) 2020년 (68/7500) → 34건
  네덜란드(NL) 2021년 (69/7500) → 34건
  네덜란드(NL) 2022년 (70/7500) → 27건
  네덜란드(NL) 2023년 (71/7500) → 33건
  네덜란드(NL) 2024년 (72/7500) → 28건
  영국(GB) 2019년 (73/7500) → 58건
  영국(GB) 2020년 (74/7500) → 46건
  영국(GB) 2021년 (75/7500) → 44건
  영국(GB) 2022년 (76/7500) → 42건
  영국(GB) 2023년 (77/7500) → 42건
  영국(GB) 2024년 (78/7500) → 41건
  폴란드(PL) 2019년 (79/7500) → 28건
  폴란드(PL) 2020년 (80/7500) → 28건
  폴란드(PL) 2021년 (81/7500) → 36건
  폴란드(PL) 2022년 (82/7500) → 36건
  폴란드(PL) 2023년 (83/7500) → 37건
  폴란드(PL) 2024년 (84/7500) → 36건
  이탈리아(IT) 2019년 (85/7500) → 29건
  이탈리아(IT) 2020년 (86/7500) → 29건
  이탈리아(IT) 2021년 (87/7500) → 29건
  이탈리아(IT) 2022년 (88/7500) → 31건
  이탈리아(IT) 2023년 (89/7500) → 29건
  이탈리아(IT) 2024년 (90/7500) → 33건
  사우디(SA) 2019년 (91/7500) → 2건
  사우디(SA) 2020년 (92/7500) → 10건
  사우디(SA) 2021년 (93/7500) → 4건
  사우디(SA) 2022년 (94/7500) → 3건
  사우디(SA) 2023년 (95/7500) → 2건
  사우디(SA) 2024년 (96/7500) → 4건
  UAE(AE) 2019년 (97/7500) → 16건
  UAE(AE) 2020년 (98/7500) → 16건
  UAE(AE) 2021년 (99/7500) → 18건
  UAE(AE) 2022년 (100/7500) → 14건
  UAE(AE) 2023년 (101/7500) → 12건
  UAE(AE) 2024년 (102/7500) → 16건
  멕시코(MX) 2019년 (103/7500) → 37건
  멕시코(MX) 2020년 (104/7500) → 43건
  멕시코(MX) 2021년 (105/7500) → 51건
  멕시코(MX) 2022년 (106/7500) → 35건
  멕시코(MX) 2023년 (107/7500) → 37건
  멕시코(MX) 2024년 (108/7500) → 39건
  캐나다(CA) 2019년 (109/7500) → 20건
  캐나다(CA) 2020년 (110/7500) → 25건
  캐나다(CA) 2021년 (111/7500) → 22건
  캐나다(CA) 2022년 (112/7500) → 19건
  캐나다(CA) 2023년 (113/7500) → 16건
  캐나다(CA) 2024년 (114/7500) → 25건
  브라질(BR) 2019년 (115/7500) → 54건
  브라질(BR) 2020년 (116/7500) → 51건
  브라질(BR) 2021년 (117/7500) → 54건
  브라질(BR) 2022년 (118/7500) → 39건
  브라질(BR) 2023년 (119/7500) → 40건
  브라질(BR) 2024년 (120/7500) → 37건
  태국(TH) 2019년 (121/7500) → 52건
  태국(TH) 2020년 (122/7500) → 64건
  태국(TH) 2021년 (123/7500) → 70건
  태국(TH) 2022년 (124/7500) → 48건
  태국(TH) 2023년 (125/7500) → 48건
  태국(TH) 2024년 (126/7500) → 47건
  인도네시아(ID) 2019년 (127/7500) → 51건
  인도네시아(ID) 2020년 (128/7500) → 48건
  인도네시아(ID) 2021년 (129/7500) → 53건
  인도네시아(ID) 2022년 (130/7500) → 38건
  인도네시아(ID) 2023년 (131/7500) → 38건
  인도네시아(ID) 2024년 (132/7500) → 46건
  필리핀(PH) 2019년 (133/7500) → 41건
  필리핀(PH) 2020년 (134/7500) → 47건
  필리핀(PH) 2021년 (135/7500) → 52건
  필리핀(PH) 2022년 (136/7500) → 46건
  필리핀(PH) 2023년 (137/7500) → 45건
  필리핀(PH) 2024년 (138/7500) → 48건
  방글라데시(BD) 2019년 (139/7500) → 12건
  방글라데시(BD) 2020년 (140/7500) → 10건
  방글라데시(BD) 2021년 (141/7500) → 9건
  방글라데시(BD) 2022년 (142/7500) → 9건
  방글라데시(BD) 2023년 (143/7500) → 11건
  방글라데시(BD) 2024년 (144/7500) → 19건
  러시아(RU) 2019년 (145/7500) → 30건
  러시아(RU) 2020년 (146/7500) → 29건
  러시아(RU) 2021년 (147/7500) → 25건
  러시아(RU) 2022년 (148/7500) → 17건
  러시아(RU) 2023년 (149/7500) → 5건
  러시아(RU) 2024년 (150/7500) → 0건

▶ [854232] 반도체_비메모리 (환율)
  미국(US) 2019년 (151/7500) → 91건
  미국(US) 2020년 (152/7500) → 86건
  미국(US) 2021년 (153/7500) → 88건
  미국(US) 2022년 (154/7500) → 78건
  미국(US) 2023년 (155/7500) → 79건
  미국(US) 2024년 (156/7500) → 76건
  중국(CN) 2019년 (157/7500) → 108건
  중국(CN) 2020년 (158/7500) → 104건
  중국(CN) 2021년 (159/7500) → 102건
  중국(CN) 2022년 (160/7500) → 84건
  중국(CN) 2023년 (161/7500) → 84건
  중국(CN) 2024년 (162/7500) → 84건
  베트남(VN) 2019년 (163/7500) → 74건
  베트남(VN) 2020년 (164/7500) → 83건
  베트남(VN) 2021년 (165/7500) → 84건
  베트남(VN) 2022년 (166/7500) → 81건
  베트남(VN) 2023년 (167/7500) → 84건
  베트남(VN) 2024년 (168/7500) → 82건
  홍콩(HK) 2019년 (169/7500) → 94건
  홍콩(HK) 2020년 (170/7500) → 95건
  홍콩(HK) 2021년 (171/7500) → 96건
  홍콩(HK) 2022년 (172/7500) → 77건
  홍콩(HK) 2023년 (173/7500) → 80건
  홍콩(HK) 2024년 (174/7500) → 80건
  일본(JP) 2019년 (175/7500) → 81건
  일본(JP) 2020년 (176/7500) → 81건
  일본(JP) 2021년 (177/7500) → 86건
  일본(JP) 2022년 (178/7500) → 79건
  일본(JP) 2023년 (179/7500) → 77건
  일본(JP) 2024년 (180/7500) → 75건
  대만(TW) 2019년 (181/7500) → 86건
  대만(TW) 2020년 (182/7500) → 87건
  대만(TW) 2021년 (183/7500) → 93건
  대만(TW) 2022년 (184/7500) → 77건
  대만(TW) 2023년 (185/7500) → 75건
  대만(TW) 2024년 (186/7500) → 82건
  인도(IN) 2019년 (187/7500) → 76건
  인도(IN) 2020년 (188/7500) → 71건
  인도(IN) 2021년 (189/7500) → 67건
  인도(IN) 2022년 (190/7500) → 61건
  인도(IN) 2023년 (191/7500) → 58건
  인도(IN) 2024년 (192/7500) → 58건
  싱가포르(SG) 2019년 (193/7500) → 74건
  싱가포르(SG) 2020년 (194/7500) → 72건
  싱가포르(SG) 2021년 (195/7500) → 80건
  싱가포르(SG) 2022년 (196/7500) → 67건
  싱가포르(SG) 2023년 (197/7500) → 69건
  싱가포르(SG) 2024년 (198/7500) → 66건
  말레이시아(MY) 2019년 (199/7500) → 74건
  말레이시아(MY) 2020년 (200/7500) → 76건
  말레이시아(MY) 2021년 (201/7500) → 78건
  말레이시아(MY) 2022년 (202/7500) → 69건
  말레이시아(MY) 2023년 (203/7500) → 72건
  말레이시아(MY) 2024년 (204/7500) → 72건
  호주(AU) 2019년 (205/7500) → 18건
  호주(AU) 2020년 (206/7500) → 16건
  호주(AU) 2021년 (207/7500) → 12건
  호주(AU) 2022년 (208/7500) → 19건
  호주(AU) 2023년 (209/7500) → 12건
  호주(AU) 2024년 (210/7500) → 12건
  독일(DE) 2019년 (211/7500) → 84건
  독일(DE) 2020년 (212/7500) → 79건
  독일(DE) 2021년 (213/7500) → 80건
  독일(DE) 2022년 (214/7500) → 62건
  독일(DE) 2023년 (215/7500) → 62건
  독일(DE) 2024년 (216/7500) → 63건
  네덜란드(NL) 2019년 (217/7500) → 56건
  네덜란드(NL) 2020년 (218/7500) → 57건
  네덜란드(NL) 2021년 (219/7500) → 57건
  네덜란드(NL) 2022년 (220/7500) → 49건
  네덜란드(NL) 2023년 (221/7500) → 42건
  네덜란드(NL) 2024년 (222/7500) → 50건
  영국(GB) 2019년 (223/7500) → 57건
  영국(GB) 2020년 (224/7500) → 46건
  영국(GB) 2021년 (225/7500) → 43건
  영국(GB) 2022년 (226/7500) → 35건
  영국(GB) 2023년 (227/7500) → 42건
  영국(GB) 2024년 (228/7500) → 42건
  폴란드(PL) 2019년 (229/7500) → 62건
  폴란드(PL) 2020년 (230/7500) → 50건
  폴란드(PL) 2021년 (231/7500) → 51건
  폴란드(PL) 2022년 (232/7500) → 52건
  폴란드(PL) 2023년 (233/7500) → 50건
  폴란드(PL) 2024년 (234/7500) → 50건
  이탈리아(IT) 2019년 (235/7500) → 15건
  이탈리아(IT) 2020년 (236/7500) → 18건
  이탈리아(IT) 2021년 (237/7500) → 21건
  이탈리아(IT) 2022년 (238/7500) → 25건
  이탈리아(IT) 2023년 (239/7500) → 19건
  이탈리아(IT) 2024년 (240/7500) → 30건
  사우디(SA) 2019년 (241/7500) → 0건
  사우디(SA) 2020년 (242/7500) → 2건
  사우디(SA) 2021년 (243/7500) → 0건
  사우디(SA) 2022년 (244/7500) → 0건
  사우디(SA) 2023년 (245/7500) → 2건
  사우디(SA) 2024년 (246/7500) → 2건
  UAE(AE) 2019년 (247/7500) → 3건
  UAE(AE) 2020년 (248/7500) → 5건
  UAE(AE) 2021년 (249/7500) → 1건
  UAE(AE) 2022년 (250/7500) → 9건
  UAE(AE) 2023년 (251/7500) → 10건
  UAE(AE) 2024년 (252/7500) → 2건
  멕시코(MX) 2019년 (253/7500) → 70건
  멕시코(MX) 2020년 (254/7500) → 60건
  멕시코(MX) 2021년 (255/7500) → 57건
  멕시코(MX) 2022년 (256/7500) → 59건
  멕시코(MX) 2023년 (257/7500) → 59건
  멕시코(MX) 2024년 (258/7500) → 58건
  캐나다(CA) 2019년 (259/7500) → 41건
  캐나다(CA) 2020년 (260/7500) → 29건
  캐나다(CA) 2021년 (261/7500) → 26건
  캐나다(CA) 2022년 (262/7500) → 36건
  캐나다(CA) 2023년 (263/7500) → 29건
  캐나다(CA) 2024년 (264/7500) → 28건
  브라질(BR) 2019년 (265/7500) → 81건
  브라질(BR) 2020년 (266/7500) → 73건
  브라질(BR) 2021년 (267/7500) → 72건
  브라질(BR) 2022년 (268/7500) → 68건
  브라질(BR) 2023년 (269/7500) → 72건
  브라질(BR) 2024년 (270/7500) → 58건
  태국(TH) 2019년 (271/7500) → 77건
  태국(TH) 2020년 (272/7500) → 77건
  태국(TH) 2021년 (273/7500) → 82건
  태국(TH) 2022년 (274/7500) → 72건
  태국(TH) 2023년 (275/7500) → 70건
  태국(TH) 2024년 (276/7500) → 74건
  인도네시아(ID) 2019년 (277/7500) → 79건
  인도네시아(ID) 2020년 (278/7500) → 70건
  인도네시아(ID) 2021년 (279/7500) → 64건
  인도네시아(ID) 2022년 (280/7500) → 69건
  인도네시아(ID) 2023년 (281/7500) → 61건
  인도네시아(ID) 2024년 (282/7500) → 61건
  필리핀(PH) 2019년 (283/7500) → 65건
  필리핀(PH) 2020년 (284/7500) → 60건
  필리핀(PH) 2021년 (285/7500) → 66건
  필리핀(PH) 2022년 (286/7500) → 61건
  필리핀(PH) 2023년 (287/7500) → 64건
  필리핀(PH) 2024년 (288/7500) → 65건
  방글라데시(BD) 2019년 (289/7500) → 4건
  방글라데시(BD) 2020년 (290/7500) → 0건
  방글라데시(BD) 2021년 (291/7500) → 0건
  방글라데시(BD) 2022년 (292/7500) → 0건
  방글라데시(BD) 2023년 (293/7500) → 3건
  방글라데시(BD) 2024년 (294/7500) → 21건
  러시아(RU) 2019년 (295/7500) → 62건
  러시아(RU) 2020년 (296/7500) → 59건
  러시아(RU) 2021년 (297/7500) → 62건
  러시아(RU) 2022년 (298/7500) → 17건
  러시아(RU) 2023년 (299/7500) → 4건
  러시아(RU) 2024년 (300/7500) → 0건

▶ [854239] 기타집적회로 (환율)
  미국(US) 2019년 (301/7500) → 72건
  미국(US) 2020년 (302/7500) → 64건
  미국(US) 2021년 (303/7500) → 64건
  미국(US) 2022년 (304/7500) → 49건
  미국(US) 2023년 (305/7500) → 48건
  미국(US) 2024년 (306/7500) → 48건
  중국(CN) 2019년 (307/7500) → 70건
  중국(CN) 2020년 (308/7500) → 77건
  중국(CN) 2021년 (309/7500) → 88건
  중국(CN) 2022년 (310/7500) → 52건
  중국(CN) 2023년 (311/7500) → 48건
  중국(CN) 2024년 (312/7500) → 48건
  베트남(VN) 2019년 (313/7500) → 63건
  베트남(VN) 2020년 (314/7500) → 79건
  베트남(VN) 2021년 (315/7500) → 79건
  베트남(VN) 2022년 (316/7500) → 47건
  베트남(VN) 2023년 (317/7500) → 48건
  베트남(VN) 2024년 (318/7500) → 48건
  홍콩(HK) 2019년 (319/7500) → 60건
  홍콩(HK) 2020년 (320/7500) → 51건
  홍콩(HK) 2021년 (321/7500) → 59건
  홍콩(HK) 2022년 (322/7500) → 48건
  홍콩(HK) 2023년 (323/7500) → 48건
  홍콩(HK) 2024년 (324/7500) → 48건
  일본(JP) 2019년 (325/7500) → 59건
  일본(JP) 2020년 (326/7500) → 61건
  일본(JP) 2021년 (327/7500) → 65건
  일본(JP) 2022년 (328/7500) → 48건
  일본(JP) 2023년 (329/7500) → 48건
  일본(JP) 2024년 (330/7500) → 48건
  대만(TW) 2019년 (331/7500) → 68건
  대만(TW) 2020년 (332/7500) → 79건
  대만(TW) 2021년 (333/7500) → 85건
  대만(TW) 2022년 (334/7500) → 48건
  대만(TW) 2023년 (335/7500) → 48건
  대만(TW) 2024년 (336/7500) → 48건
  인도(IN) 2019년 (337/7500) → 47건
  인도(IN) 2020년 (338/7500) → 51건
  인도(IN) 2021년 (339/7500) → 45건
  인도(IN) 2022년 (340/7500) → 36건
  인도(IN) 2023년 (341/7500) → 38건
  인도(IN) 2024년 (342/7500) → 36건
  싱가포르(SG) 2019년 (343/7500) → 54건
  싱가포르(SG) 2020년 (344/7500) → 57건
  싱가포르(SG) 2021년 (345/7500) → 59건
  싱가포르(SG) 2022년 (346/7500) → 42건
  싱가포르(SG) 2023년 (347/7500) → 44건
  싱가포르(SG) 2024년 (348/7500) → 47건
  말레이시아(MY) 2019년 (349/7500) → 68건
  말레이시아(MY) 2020년 (350/7500) → 63건
  말레이시아(MY) 2021년 (351/7500) → 68건
  말레이시아(MY) 2022년 (352/7500) → 48건
  말레이시아(MY) 2023년 (353/7500) → 48건
  말레이시아(MY) 2024년 (354/7500) → 48건
  호주(AU) 2019년 (355/7500) → 15건
  호주(AU) 2020년 (356/7500) → 16건
  호주(AU) 2021년 (357/7500) → 19건
  호주(AU) 2022년 (358/7500) → 19건
  호주(AU) 2023년 (359/7500) → 16건
  호주(AU) 2024년 (360/7500) → 19건
  독일(DE) 2019년 (361/7500) → 46건
  독일(DE) 2020년 (362/7500) → 46건
  독일(DE) 2021년 (363/7500) → 42건
  독일(DE) 2022년 (364/7500) → 41건
  독일(DE) 2023년 (365/7500) → 39건
  독일(DE) 2024년 (366/7500) → 41건
  네덜란드(NL) 2019년 (367/7500) → 26건
  네덜란드(NL) 2020년 (368/7500) → 24건
  네덜란드(NL) 2021년 (369/7500) → 24건
  네덜란드(NL) 2022년 (370/7500) → 25건
  네덜란드(NL) 2023년 (371/7500) → 25건
  네덜란드(NL) 2024년 (372/7500) → 25건
  영국(GB) 2019년 (373/7500) → 33건
  영국(GB) 2020년 (374/7500) → 42건
  영국(GB) 2021년 (375/7500) → 39건
  영국(GB) 2022년 (376/7500) → 36건
  영국(GB) 2023년 (377/7500) → 35건
  영국(GB) 2024년 (378/7500) → 33건
  폴란드(PL) 2019년 (379/7500) → 23건
  폴란드(PL) 2020년 (380/7500) → 23건
  폴란드(PL) 2021년 (381/7500) → 31건
  폴란드(PL) 2022년 (382/7500) → 36건
  폴란드(PL) 2023년 (383/7500) → 33건
  폴란드(PL) 2024년 (384/7500) → 30건
  이탈리아(IT) 2019년 (385/7500) → 19건
  이탈리아(IT) 2020년 (386/7500) → 20건
  이탈리아(IT) 2021년 (387/7500) → 23건
  이탈리아(IT) 2022년 (388/7500) → 17건
  이탈리아(IT) 2023년 (389/7500) → 18건
  이탈리아(IT) 2024년 (390/7500) → 27건
  사우디(SA) 2019년 (391/7500) → 1건
  사우디(SA) 2020년 (392/7500) → 0건
  사우디(SA) 2021년 (393/7500) → 1건
  사우디(SA) 2022년 (394/7500) → 2건
  사우디(SA) 2023년 (395/7500) → 2건
  사우디(SA) 2024년 (396/7500) → 2건
  UAE(AE) 2019년 (397/7500) → 10건
  UAE(AE) 2020년 (398/7500) → 14건
  UAE(AE) 2021년 (399/7500) → 12건
  UAE(AE) 2022년 (400/7500) → 15건
  UAE(AE) 2023년 (401/7500) → 13건
  UAE(AE) 2024년 (402/7500) → 9건
  멕시코(MX) 2019년 (403/7500) → 48건
  멕시코(MX) 2020년 (404/7500) → 52건
  멕시코(MX) 2021년 (405/7500) → 60건
  멕시코(MX) 2022년 (406/7500) → 46건
  멕시코(MX) 2023년 (407/7500) → 48건
  멕시코(MX) 2024년 (408/7500) → 47건
  캐나다(CA) 2019년 (409/7500) → 20건
  캐나다(CA) 2020년 (410/7500) → 21건
  캐나다(CA) 2021년 (411/7500) → 21건
  캐나다(CA) 2022년 (412/7500) → 20건
  캐나다(CA) 2023년 (413/7500) → 21건
  캐나다(CA) 2024년 (414/7500) → 22건
  브라질(BR) 2019년 (415/7500) → 47건
  브라질(BR) 2020년 (416/7500) → 44건
  브라질(BR) 2021년 (417/7500) → 48건
  브라질(BR) 2022년 (418/7500) → 37건
  브라질(BR) 2023년 (419/7500) → 40건
  브라질(BR) 2024년 (420/7500) → 38건
  태국(TH) 2019년 (421/7500) → 54건
  태국(TH) 2020년 (422/7500) → 60건
  태국(TH) 2021년 (423/7500) → 61건
  태국(TH) 2022년 (424/7500) → 48건
  태국(TH) 2023년 (425/7500) → 48건
  태국(TH) 2024년 (426/7500) → 48건
  인도네시아(ID) 2019년 (427/7500) → 45건
  인도네시아(ID) 2020년 (428/7500) → 50건
  인도네시아(ID) 2021년 (429/7500) → 55건
  인도네시아(ID) 2022년 (430/7500) → 42건
  인도네시아(ID) 2023년 (431/7500) → 45건
  인도네시아(ID) 2024년 (432/7500) → 38건
  필리핀(PH) 2019년 (433/7500) → 49건
  필리핀(PH) 2020년 (434/7500) → 51건
  필리핀(PH) 2021년 (435/7500) → 56건
  필리핀(PH) 2022년 (436/7500) → 43건
  필리핀(PH) 2023년 (437/7500) → 46건
  필리핀(PH) 2024년 (438/7500) → 47건
  방글라데시(BD) 2019년 (439/7500) → 1건
  방글라데시(BD) 2020년 (440/7500) → 0건
  방글라데시(BD) 2021년 (441/7500) → 3건
  방글라데시(BD) 2022년 (442/7500) → 0건
  방글라데시(BD) 2023년 (443/7500) → 5건
  방글라데시(BD) 2024년 (444/7500) → 12건
  러시아(RU) 2019년 (445/7500) → 34건
  러시아(RU) 2020년 (446/7500) → 40건
  러시아(RU) 2021년 (447/7500) → 41건
  러시아(RU) 2022년 (448/7500) → 21건
  러시아(RU) 2023년 (449/7500) → 8건
  러시아(RU) 2024년 (450/7500) → 2건

▶ [851762] 통신기기부품 (환율)
  미국(US) 2019년 (451/7500) → 307건
  미국(US) 2020년 (452/7500) → 309건
  미국(US) 2021년 (453/7500) → 307건
  미국(US) 2022년 (454/7500) → 116건
  미국(US) 2023년 (455/7500) → 109건
  미국(US) 2024년 (456/7500) → 108건
  중국(CN) 2019년 (457/7500) → 335건
  중국(CN) 2020년 (458/7500) → 339건
  중국(CN) 2021년 (459/7500) → 344건
  중국(CN) 2022년 (460/7500) → 132건
  중국(CN) 2023년 (461/7500) → 108건
  중국(CN) 2024년 (462/7500) → 108건
  베트남(VN) 2019년 (463/7500) → 172건
  베트남(VN) 2020년 (464/7500) → 187건
  베트남(VN) 2021년 (465/7500) → 197건
  베트남(VN) 2022년 (466/7500) → 97건
  베트남(VN) 2023년 (467/7500) → 103건
  베트남(VN) 2024년 (468/7500) → 105건
  홍콩(HK) 2019년 (469/7500) → 195건
  홍콩(HK) 2020년 (470/7500) → 190건
  홍콩(HK) 2021년 (471/7500) → 188건
  홍콩(HK) 2022년 (472/7500) → 104건
  홍콩(HK) 2023년 (473/7500) → 100건
  홍콩(HK) 2024년 (474/7500) → 99건
  일본(JP) 2019년 (475/7500) → 263건
  일본(JP) 2020년 (476/7500) → 266건
  일본(JP) 2021년 (477/7500) → 258건
  일본(JP) 2022년 (478/7500) → 110건
  일본(JP) 2023년 (479/7500) → 104건
  일본(JP) 2024년 (480/7500) → 107건
  대만(TW) 2019년 (481/7500) → 251건
  대만(TW) 2020년 (482/7500) → 265건
  대만(TW) 2021년 (483/7500) → 241건
  대만(TW) 2022년 (484/7500) → 107건
  대만(TW) 2023년 (485/7500) → 103건
  대만(TW) 2024년 (486/7500) → 101건
  인도(IN) 2019년 (487/7500) → 151건
  인도(IN) 2020년 (488/7500) → 132건
  인도(IN) 2021년 (489/7500) → 126건
  인도(IN) 2022년 (490/7500) → 88건
  인도(IN) 2023년 (491/7500) → 90건
  인도(IN) 2024년 (492/7500) → 88건
  싱가포르(SG) 2019년 (493/7500) → 232건
  싱가포르(SG) 2020년 (494/7500) → 231건
  싱가포르(SG) 2021년 (495/7500) → 217건
  싱가포르(SG) 2022년 (496/7500) → 99건
  싱가포르(SG) 2023년 (497/7500) → 99건
  싱가포르(SG) 2024년 (498/7500) → 97건
  말레이시아(MY) 2019년 (499/7500) → 194건
  말레이시아(MY) 2020년 (500/7500) → 197건
  말레이시아(MY) 2021년 (501/7500) → 186건
  말레이시아(MY) 2022년 (502/7500) → 104건
  말레이시아(MY) 2023년 (503/7500) → 100건
  말레이시아(MY) 2024년 (504/7500) → 98건
  호주(AU) 2019년 (505/7500) → 140건
  호주(AU) 2020년 (506/7500) → 143건
  호주(AU) 2021년 (507/7500) → 142건
  호주(AU) 2022년 (508/7500) → 96건
  호주(AU) 2023년 (509/7500) → 96건
  호주(AU) 2024년 (510/7500) → 90건
  독일(DE) 2019년 (511/7500) → 206건
  독일(DE) 2020년 (512/7500) → 230건
  독일(DE) 2021년 (513/7500) → 223건
  독일(DE) 2022년 (514/7500) → 106건
  독일(DE) 2023년 (515/7500) → 104건
  독일(DE) 2024년 (516/7500) → 101건
  네덜란드(NL) 2019년 (517/7500) → 147건
  네덜란드(NL) 2020년 (518/7500) → 135건
  네덜란드(NL) 2021년 (519/7500) → 147건
  네덜란드(NL) 2022년 (520/7500) → 99건
  네덜란드(NL) 2023년 (521/7500) → 99건
  네덜란드(NL) 2024년 (522/7500) → 91건
  영국(GB) 2019년 (523/7500) → 173건
  영국(GB) 2020년 (524/7500) → 175건
  영국(GB) 2021년 (525/7500) → 161건
  영국(GB) 2022년 (526/7500) → 99건
  영국(GB) 2023년 (527/7500) → 95건
  영국(GB) 2024년 (528/7500) → 90건
  폴란드(PL) 2019년 (529/7500) → 119건
  폴란드(PL) 2020년 (530/7500) → 125건
  폴란드(PL) 2021년 (531/7500) → 109건
  폴란드(PL) 2022년 (532/7500) → 90건
  폴란드(PL) 2023년 (533/7500) → 90건
  폴란드(PL) 2024년 (534/7500) → 95건
  이탈리아(IT) 2019년 (535/7500) → 98건
  이탈리아(IT) 2020년 (536/7500) → 94건
  이탈리아(IT) 2021년 (537/7500) → 110건
  이탈리아(IT) 2022년 (538/7500) → 74건
  이탈리아(IT) 2023년 (539/7500) → 63건
  이탈리아(IT) 2024년 (540/7500) → 71건
  사우디(SA) 2019년 (541/7500) → 60건
  사우디(SA) 2020년 (542/7500) → 70건
  사우디(SA) 2021년 (543/7500) → 66건
  사우디(SA) 2022년 (544/7500) → 50건
  사우디(SA) 2023년 (545/7500) → 51건
  사우디(SA) 2024년 (546/7500) → 48건
  UAE(AE) 2019년 (547/7500) → 102건
  UAE(AE) 2020년 (548/7500) → 119건
  UAE(AE) 2021년 (549/7500) → 105건
  UAE(AE) 2022년 (550/7500) → 86건
  UAE(AE) 2023년 (551/7500) → 73건
  UAE(AE) 2024년 (552/7500) → 77건
  멕시코(MX) 2019년 (553/7500) → 147건
  멕시코(MX) 2020년 (554/7500) → 159건
  멕시코(MX) 2021년 (555/7500) → 162건
  멕시코(MX) 2022년 (556/7500) → 100건
  멕시코(MX) 2023년 (557/7500) → 99건
  멕시코(MX) 2024년 (558/7500) → 96건
  캐나다(CA) 2019년 (559/7500) → 104건
  캐나다(CA) 2020년 (560/7500) → 132건
  캐나다(CA) 2021년 (561/7500) → 119건
  캐나다(CA) 2022년 (562/7500) → 90건
  캐나다(CA) 2023년 (563/7500) → 89건
  캐나다(CA) 2024년 (564/7500) → 91건
  브라질(BR) 2019년 (565/7500) → 81건
  브라질(BR) 2020년 (566/7500) → 67건
  브라질(BR) 2021년 (567/7500) → 69건
  브라질(BR) 2022년 (568/7500) → 68건
  브라질(BR) 2023년 (569/7500) → 64건
  브라질(BR) 2024년 (570/7500) → 57건
  태국(TH) 2019년 (571/7500) → 168건
  태국(TH) 2020년 (572/7500) → 184건
  태국(TH) 2021년 (573/7500) → 186건
  태국(TH) 2022년 (574/7500) → 104건
  태국(TH) 2023년 (575/7500) → 99건
  태국(TH) 2024년 (576/7500) → 92건
  인도네시아(ID) 2019년 (577/7500) → 89건
  인도네시아(ID) 2020년 (578/7500) → 116건
  인도네시아(ID) 2021년 (579/7500) → 129건
  인도네시아(ID) 2022년 (580/7500) → 89건
  인도네시아(ID) 2023년 (581/7500) → 83건
  인도네시아(ID) 2024년 (582/7500) → 88건
  필리핀(PH) 2019년 (583/7500) → 113건
  필리핀(PH) 2020년 (584/7500) → 125건
  필리핀(PH) 2021년 (585/7500) → 135건
  필리핀(PH) 2022년 (586/7500) → 86건
  필리핀(PH) 2023년 (587/7500) → 80건
  필리핀(PH) 2024년 (588/7500) → 91건
  방글라데시(BD) 2019년 (589/7500) → 20건
  방글라데시(BD) 2020년 (590/7500) → 14건
  방글라데시(BD) 2021년 (591/7500) → 17건
  방글라데시(BD) 2022년 (592/7500) → 20건
  방글라데시(BD) 2023년 (593/7500) → 22건
  방글라데시(BD) 2024년 (594/7500) → 20건
  러시아(RU) 2019년 (595/7500) → 100건
  러시아(RU) 2020년 (596/7500) → 83건
  러시아(RU) 2021년 (597/7500) → 97건
  러시아(RU) 2022년 (598/7500) → 51건
  러시아(RU) 2023년 (599/7500) → 46건

- 오류 항목 다시 불러오고 병합

In [11]:
import requests
import pandas as pd
import xml.etree.ElementTree as ET
import time
import os

# ================================================
# STEP 1. 기본 설정
# ================================================

API_KEY        = "d14e288e04bef1da401d66602694b68e03f685e96b078e003b3091eeb8bb8210"
API_URL        = "http://apis.data.go.kr/1220000/nitemtrade/getNitemtradeList"

ORIGINAL_FILE  = "trade_data_final.csv"   # 기존 수집 파일
RETRY_FILE     = "trade_data_retry.csv"   # 재수집 결과
MERGED_FILE    = "trade_data_merged.csv"  # 최종 병합 결과

# HS코드 → (품목명, 충격유형) 매핑
HS_INFO = {
    "854231": ("반도체_메모리",       "환율"),
    "854232": ("반도체_비메모리",     "환율"),
    "854239": ("기타집적회로",        "환율"),
    "851762": ("통신기기부품",        "환율"),
    "851769": ("기타통신기기",        "환율"),
    "852872": ("평판디스플레이",      "환율"),
    "870321": ("승용차_1000cc이하",   "환율"),
    "870322": ("승용차_1000~1500cc", "환율"),
    "870323": ("승용차_1500~3000cc", "환율"),
    "870324": ("승용차_3000cc초과",   "환율"),
    "870840": ("자동차변속기",        "환율"),
    "870850": ("자동차구동축",        "환율"),
    "870899": ("기타자동차부품",      "환율"),
    "901380": ("광학기기",            "환율"),
    "903289": ("계측제어기기",        "환율"),
    "271012": ("경유등유",            "유가"),
    "271019": ("기타석유제품",        "유가"),
    "271111": ("LPG액화",             "유가"),
    "271121": ("LNG액화",             "유가"),
    "290110": ("에틸렌",              "유가"),
    "290121": ("에틸렌기타",          "유가"),
    "290129": ("기타기초유분",        "유가"),
    "390110": ("폴리에틸렌저밀도",    "유가"),
    "390120": ("폴리에틸렌고밀도",    "유가"),
    "390210": ("폴리프로필렌",        "유가"),
    "390410": ("PVC",                 "유가"),
    "390761": ("PET",                 "유가"),   # 390760 → 390761 교체
    "330499": ("화장품기타",          "유가"),
    "320419": ("합성염료",            "유가"),
    "381400": ("혼합용제희석제",      "유가"),
    "847989": ("일반기계기타",        "금리"),
    "847950": ("산업용로봇",          "금리"),
    "842951": ("불도저굴착기",        "금리"),
    "842952": ("스크레이퍼",          "금리"),
    "890190": ("선박기타",            "금리"),
    "890120": ("탱커",                "금리"),
    "890130": ("냉동선",              "금리"),
    "720826": ("열연강판",            "금리"),
    "720839": ("냉연강판",            "금리"),
    "730511": ("강관",                "금리"),
    "850760": ("리튬이온이차전지",    "복합"),
    "850780": ("기타이차전지",        "복합"),
    "848620": ("반도체제조장비",      "복합"),
    "848630": ("반도체공정장비",      "복합"),
    "300490": ("의약품기타",          "복합"),
    "300420": ("항생제",              "복합"),
    "880240": ("항공기",              "복합"),
    "880330": ("항공기부품",          "복합"),
    "854140": ("태양전지",            "복합"),
    "902780": ("분석기기",            "복합"),
}

COUNTRY_INFO = {
    "US": "미국",       "CN": "중국",       "VN": "베트남",
    "HK": "홍콩",       "JP": "일본",       "TW": "대만",
    "IN": "인도",       "SG": "싱가포르",   "MY": "말레이시아",
    "AU": "호주",       "DE": "독일",       "NL": "네덜란드",
    "GB": "영국",       "PL": "폴란드",     "IT": "이탈리아",
    "SA": "사우디",     "AE": "UAE",        "MX": "멕시코",
    "CA": "캐나다",     "BR": "브라질",     "TH": "태국",
    "ID": "인도네시아", "PH": "필리핀",     "BD": "방글라데시",
    "RU": "러시아",
}


# ================================================
# STEP 2. 재수집 대상
# ================================================

# ① 타임아웃 오류 110건
TIMEOUT_TARGETS = [
    ("851769", "SA", 2021), ("852872", "DE", 2021), ("852872", "GB", 2023),
    ("870321", "US", 2019), ("870322", "US", 2019), ("870323", "JP", 2021),
    ("870323", "AU", 2024), ("870324", "VN", 2023), ("870840", "CN", 2021),
    ("870840", "TW", 2020), ("870840", "DE", 2024), ("870850", "IN", 2022),
    ("870850", "SA", 2023), ("870850", "ID", 2021), ("870850", "BD", 2020),
    ("870899", "TW", 2019), ("870899", "TW", 2020), ("901380", "VN", 2023),
    ("271012", "DE", 2023), ("271012", "IT", 2020), ("271012", "AE", 2019),
    ("271012", "AE", 2024), ("271019", "JP", 2019), ("271019", "JP", 2023),
    ("271019", "SG", 2023), ("271019", "AU", 2022), ("271019", "NL", 2023),
    ("271111", "NL", 2020), ("271121", "MY", 2024), ("290110", "NL", 2023),
    ("290121", "PL", 2023), ("290121", "MX", 2022), ("290129", "CN", 2019),
    ("290129", "DE", 2022), ("290129", "CA", 2023), ("390110", "AU", 2024),
    ("390110", "MX", 2022), ("390120", "DE", 2019), ("390210", "MY", 2023),
    ("390210", "IT", 2021), ("390410", "SG", 2022), ("390410", "BD", 2019),
    ("390760", "US", 2022), ("390760", "SG", 2024), ("390760", "GB", 2023),
    ("390760", "RU", 2019), ("330499", "US", 2021), ("330499", "MY", 2020),
    ("330499", "AE", 2023), ("320419", "IT", 2021), ("381400", "DE", 2023),
    ("381400", "RU", 2022), ("847989", "NL", 2023), ("847950", "CN", 2021),
    ("847950", "MY", 2022), ("847950", "CA", 2024), ("847950", "BD", 2019),
    ("842951", "PL", 2021), ("842951", "ID", 2024), ("842952", "MX", 2019),
    ("842952", "CA", 2024), ("890190", "TW", 2021), ("890190", "AE", 2019),
    ("890190", "AE", 2021), ("890120", "TW", 2020), ("890130", "US", 2020),
    ("890130", "CN", 2019), ("890130", "DE", 2022), ("890130", "CA", 2023),
    ("720826", "US", 2020), ("720826", "VN", 2023), ("720826", "IN", 2024),
    ("720826", "AU", 2021), ("720826", "GB", 2022), ("720826", "CA", 2020),
    ("720839", "HK", 2020), ("720839", "AU", 2021), ("720839", "GB", 2022),
    ("720839", "AE", 2023), ("720839", "ID", 2021), ("720839", "RU", 2021),
    ("730511", "BD", 2021), ("850760", "JP", 2019), ("850780", "DE", 2020),
    ("850780", "IT", 2023), ("848620", "CN", 2022), ("848620", "NL", 2023),
    ("848620", "PL", 2019), ("848620", "ID", 2019), ("848630", "AU", 2021),
    ("848630", "DE", 2023), ("848630", "NL", 2022), ("848630", "IT", 2019),
    ("848630", "IT", 2024), ("848630", "AE", 2020), ("848630", "BD", 2021),
    ("300490", "US", 2024), ("300490", "MY", 2022), ("300490", "BD", 2024),
    ("300420", "CN", 2023), ("300420", "PL", 2019), ("300420", "ID", 2019),
    ("880240", "IT", 2024), ("880330", "CN", 2022), ("880330", "TW", 2020),
    ("880330", "SA", 2020), ("880330", "BR", 2022), ("854140", "RU", 2024),
    ("902780", "BR", 2022), ("902780", "RU", 2023),
]

# ② PET 교체 (390760 → 390761) 전체 25개국 x 6년
COUNTRIES = list(COUNTRY_INFO.keys())
PET_TARGETS = [
    ("390761", c, y)
    for c in COUNTRIES
    for y in range(2019, 2025)
]

# 전체 재수집 대상 합치기
ALL_TARGETS = TIMEOUT_TARGETS + PET_TARGETS

print(f"타임아웃 오류: {len(TIMEOUT_TARGETS)}건")
print(f"PET 교체 수집: {len(PET_TARGETS)}건")
print(f"총 재수집 대상: {len(ALL_TARGETS)}건")


# ================================================
# STEP 3. API 호출 함수
# ================================================

def get_one(hs_code, country_code, year, max_retry=3):
    params = {
        "serviceKey": API_KEY,
        "strtYymm":   f"{year}01",
        "endYymm":    f"{year}12",
        "hsSgn":      hs_code,
        "cntyCd":     country_code,
    }

    for attempt in range(1, max_retry + 1):
        try:
            resp = requests.get(API_URL, params=params, timeout=15)
            resp.raise_for_status()
            root  = ET.fromstring(resp.text)
            items = root.findall(".//item")
            result = []
            for item in items:
                year_val = item.findtext("year", "")
                if year_val == "총계":
                    continue
                result.append({
                    "year":        year_val,
                    "expDlr":      item.findtext("expDlr",      "0"),
                    "expWgt":      item.findtext("expWgt",      "0"),
                    "impDlr":      item.findtext("impDlr",      "0"),
                    "impWgt":      item.findtext("impWgt",      "0"),
                    "balPayments": item.findtext("balPayments", "0"),
                })
            return result

        except ET.ParseError:
            print(f"  ⚠️  XML 파싱 오류: {resp.text[:100]}")
            return []

        except Exception as e:
            if attempt < max_retry:
                wait = attempt * 5
                print(f"  ⚠️  재시도 {attempt}/{max_retry} → {wait}초 대기...")
                time.sleep(wait)
            else:
                print(f"  ❌  최종 실패: {e}")
                return []


# ================================================
# STEP 4. 재수집 실행
# ================================================

def retry_collect():
    result = []
    total  = len(ALL_TARGETS)

    print(f"\n{'='*50}")
    print(f"재수집 시작 (총 {total}건)")
    print(f"{'='*50}")

    for i, (hs_code, country_code, year) in enumerate(ALL_TARGETS, 1):
        hs_name, shock_type = HS_INFO.get(hs_code, ("미분류", "기타"))
        country_name        = COUNTRY_INFO.get(country_code, country_code)

        # 구분선 출력 (타임아웃→PET 전환 시)
        if i == len(TIMEOUT_TARGETS) + 1:
            print(f"\n{'='*50}")
            print("▶ PET (390761) 신규 수집 시작")
            print(f"{'='*50}")

        print(f"  ({i}/{total}) [{hs_code}] {country_name}({country_code}) {year}년", end=" ")

        items = get_one(hs_code, country_code, year)

        for item in items:
            year_month = item["year"].replace(".", "-")
            result.append({
                "연월":     year_month,
                "연도":     year_month[:4],
                "월":       year_month[5:7],
                "HS코드":   hs_code,
                "품목명":   hs_name,
                "충격유형": shock_type,
                "국가코드": country_code,
                "국가명":   country_name,
                "수출금액": item["expDlr"],
                "수출중량": item["expWgt"],
                "수입금액": item["impDlr"],
                "수입중량": item["impWgt"],
                "무역수지": item["balPayments"],
            })

        print(f"→ {len(items)}건")
        time.sleep(0.3)

    return pd.DataFrame(result)


# ================================================
# STEP 5. 병합
# ================================================

def merge(df_retry):

    if not os.path.exists(ORIGINAL_FILE):
        print(f"⚠️  기존 파일({ORIGINAL_FILE})이 없습니다.")
        return df_retry

    df_original = pd.read_csv(ORIGINAL_FILE, dtype=str)
    print(f"\n기존 데이터:   {len(df_original):,}행")
    print(f"재수집 데이터: {len(df_retry):,}행")

    # 기존 데이터에서 390760(PET 구버전) 제거
    before = len(df_original)
    df_original = df_original[df_original["HS코드"] != "390760"]
    removed = before - len(df_original)
    if removed > 0:
        print(f"기존 390760(PET 구버전) 제거: {removed}행")

    # 재수집 데이터 타입 맞추기
    df_retry = df_retry.astype(str)

    # 병합
    df_merged = pd.concat([df_original, df_retry], ignore_index=True)

    # 중복 제거 (연월+HS코드+국가코드 기준, 재수집 우선)
    before = len(df_merged)
    df_merged = df_merged.drop_duplicates(
        subset=["연월", "HS코드", "국가코드"], keep="last"
    )
    print(f"중복 제거:     {before - len(df_merged)}행")

    # 숫자형 변환 및 정렬
    for col in ["수출금액", "수출중량", "수입금액", "수입중량", "무역수지"]:
        df_merged[col] = pd.to_numeric(df_merged[col], errors="coerce").fillna(0)

    df_merged["날짜"] = pd.to_datetime(df_merged["연월"], format="%Y-%m", errors="coerce")
    df_merged = df_merged.sort_values(
        ["충격유형", "HS코드", "국가코드", "날짜"]
    ).reset_index(drop=True)

    df_merged.to_csv(MERGED_FILE, index=False, encoding="utf-8-sig")

    print(f"\n{'='*50}")
    print(f"✅ 병합 완료: {MERGED_FILE}")
    print(f"   최종 행수: {len(df_merged):,}행")
    print(f"\n▶ HS코드별 행수 (상위 10개):")
    print(df_merged.groupby(["HS코드","품목명"])["연월"].count()
          .sort_values(ascending=False).head(10).to_string())

    return df_merged


# ================================================
# 실행
# ================================================

if __name__ == "__main__":

    print("=" * 50)
    print("재수집 및 병합 시작")
    print(f"  타임아웃 오류: {len(TIMEOUT_TARGETS)}건")
    print(f"  PET 교체 수집: {len(PET_TARGETS)}건 (390760→390761)")
    print(f"  총 API 호출:   {len(ALL_TARGETS)}건")
    print("=" * 50)

    # 재수집
    df_retry = retry_collect()

    # 재수집 결과 저장
    if not df_retry.empty:
        df_retry.to_csv(RETRY_FILE, index=False, encoding="utf-8-sig")
        print(f"\n재수집 결과 저장: {RETRY_FILE} ({len(df_retry):,}행)")

    # 병합
    print(f"\n{'='*50}")
    print("기존 데이터와 병합 중...")
    df_merged = merge(df_retry)

타임아웃 오류: 110건
PET 교체 수집: 150건
총 재수집 대상: 260건
==================================================
재수집 및 병합 시작
  타임아웃 오류: 110건
  PET 교체 수집: 150건 (390760→390761)
  총 API 호출:   260건
==================================================

==================================================
재수집 시작 (총 260건)
==================================================
  (1/260) [851769] 사우디(SA) 2021년 → 8건
  (2/260) [852872] 독일(DE) 2021년 → 31건
  (3/260) [852872] 영국(GB) 2023년 → 24건
  (4/260) [870321] 미국(US) 2019년 → 9건
  (5/260) [870322] 미국(US) 2019년 → 21건
  (6/260) [870323] 일본(JP) 2021년 → 48건
  (7/260) [870323] 호주(AU) 2024년 → 24건
  (8/260) [870324] 베트남(VN) 2023년 → 4건
  (9/260) [870840] 중국(CN) 2021년 → 12건
  (10/260) [870840] 대만(TW) 2020년 → 12건
  (11/260) [870840] 독일(DE) 2024년 → 12건
  (12/260) [870850] 인도(IN) 2022년 → 24건
  (13/260) [870850] 사우디(SA) 2023년 → 4건
  (14/260) [870850] 인도네시아(ID) 2021년 → 24건
  (15/260) [870850] 방글라데시(BD) 2020년 → 4건
  (16/260) [870899] 대만(TW) 2019년 → 28건
  (17/260) [870899] 대만(TW) 2020년 → 24건
  (18/260) [901380] 베트남(VN) 2023년 → 24건
  (19/260) [271012] 독일(DE) 2023년 → 17건
  (20/260) [271012] 이탈리아(IT) 2020년 → 8건
  (21/260) [271012] UAE(AE) 2019년 → 17건
  (22/260) [271012] UAE(AE) 2024년 → 18건
  (23/260) [271019] 일본(JP) 2019년 → 354건
  (24/260) [271019] 일본(JP) 2023년 → 364건
  (25/260) [271019] 싱가포르(SG) 2023년 → 263건
  (26/260) [271019] 호주(AU) 2022년 → 175건
  (27/260) [271019] 네덜란드(NL) 2023년 → 127건
  (28/260) [271111] 네덜란드(NL) 2020년 → 0건
  (29/260) [271121] 말레이시아(MY) 2024년 → 9건
  (30/260) [290110] 네덜란드(NL) 2023년 → 9건
  (31/260) [290121] 폴란드(PL) 2023년 → 0건
  (32/260) [290121] 멕시코(MX) 2022년 → 0건
  (33/260) [290129] 중국(CN) 2019년 → 19건
  (34/260) [290129] 독일(DE) 2022년 → 12건
  (35/260) [290129] 캐나다(CA) 2023년 → 22건
  (36/260) [390110] 호주(AU) 2024년 → 17건
  (37/260) [390110] 멕시코(MX) 2022년 → 22건
  (38/260) [390120] 독일(DE) 2019년 → 14건
  (39/260) [390210] 말레이시아(MY) 2023년 → 12건
  (40/260) [390210] 이탈리아(IT) 2021년 → 12건
  (41/260) [390410] 싱가포르(SG) 2022년 → 12건
  (42/260) [390410] 방글라데시(BD) 2019년 → 11건
  (43/260) [390760] 미국(US) 2022년 → 0건
  (44/260) [390760] 싱가포르(SG) 2024년 → 0건
  (45/260) [390760] 영국(GB) 2023년 → 0건
  (46/260) [390760] 러시아(RU) 2019년 → 0건
  (47/260) [330499] 미국(US) 2021년 → 48건
  (48/260) [330499] 말레이시아(MY) 2020년 → 48건
  (49/260) [330499] UAE(AE) 2023년 → 40건
  (50/260) [320419] 이탈리아(IT) 2021년 → 10건
  (51/260) [381400] 독일(DE) 2023년 → 48건
  (52/260) [381400] 러시아(RU) 2022년 → 15건
  (53/260) [847989] 네덜란드(NL) 2023년 → 50건
  (54/260) [847950] 중국(CN) 2021년 → 24건
  (55/260) [847950] 말레이시아(MY) 2022년 → 13건
  (56/260) [847950] 캐나다(CA) 2024년 → 13건
  (57/260) [847950] 방글라데시(BD) 2019년 → 1건
  (58/260) [842951] 폴란드(PL) 2021년 → 1건
  (59/260) [842951] 인도네시아(ID) 2024년 → 6건
  (60/260) [842952] 멕시코(MX) 2019년 → 11건
  (61/260) [842952] 캐나다(CA) 2024년 → 12건
  (62/260) [890190] 대만(TW) 2021년 → 4건
  (63/260) [890190] UAE(AE) 2019년 → 3건
  (64/260) [890190] UAE(AE) 2021년 → 2건
  (65/260) [890120] 대만(TW) 2020년 → 0건
  (66/260) [890130] 미국(US) 2020년 → 0건
  (67/260) [890130] 중국(CN) 2019년 → 3건
  (68/260) [890130] 독일(DE) 2022년 → 0건
  (69/260) [890130] 캐나다(CA) 2023년 → 0건
  (70/260) [720826] 미국(US) 2020년 → 20건
  (71/260) [720826] 베트남(VN) 2023년 → 16건
  (72/260) [720826] 인도(IN) 2024년 → 24건
  (73/260) [720826] 호주(AU) 2021년 → 1건
  (74/260) [720826] 영국(GB) 2022년 → 0건
  (75/260) [720826] 캐나다(CA) 2020년 → 4건
  (76/260) [720839] 홍콩(HK) 2020년 → 0건
  (77/260) [720839] 호주(AU) 2021년 → 16건
  (78/260) [720839] 영국(GB) 2022년 → 7건
  (79/260) [720839] UAE(AE) 2023년 → 7건
  (80/260) [720839] 인도네시아(ID) 2021년 → 13건
  (81/260) [720839] 러시아(RU) 2021년 → 1건
  (82/260) [730511] 방글라데시(BD) 2021년 → 1건
  (83/260) [850760] 일본(JP) 2019년 → 24건
  (84/260) [850780] 독일(DE) 2020년 → 12건
  (85/260) [850780] 이탈리아(IT) 2023년 → 10건
  (86/260) [848620] 중국(CN) 2022년 → 222건
  (87/260) [848620] 네덜란드(NL) 2023년 → 50건
  (88/260) [848620] 폴란드(PL) 2019년 → 10건
  (89/260) [848620] 인도네시아(ID) 2019년 → 10건
  (90/260) [848630] 호주(AU) 2021년 → 4건
  (91/260) [848630] 독일(DE) 2023년 → 3건
  (92/260) [848630] 네덜란드(NL) 2022년 → 0건
  (93/260) [848630] 이탈리아(IT) 2019년 → 1건
  (94/260) [848630] 이탈리아(IT) 2024년 → 3건
  (95/260) [848630] UAE(AE) 2020년 → 1건
  (96/260) [848630] 방글라데시(BD) 2021년 → 0건
  (97/260) [300490] 미국(US) 2024년 → 45건
  (98/260) [300490] 말레이시아(MY) 2022년 → 22건
  (99/260) [300490] 방글라데시(BD) 2024년 → 14건
  (100/260) [300420] 중국(CN) 2023년 → 23건
  (101/260) [300420] 폴란드(PL) 2019년 → 0건
  (102/260) [300420] 인도네시아(ID) 2019년 → 8건
  (103/260) [880240] 이탈리아(IT) 2024년 → 0건
  (104/260) [880330] 중국(CN) 2022년 → 0건
  (105/260) [880330] 대만(TW) 2020년 → 15건
  (106/260) [880330] 사우디(SA) 2020년 → 9건
  (107/260) [880330] 브라질(BR) 2022년 → 0건
  (108/260) [854140] 러시아(RU) 2024년 → 0건
  (109/260) [902780] 브라질(BR) 2022년 → 0건
  (110/260) [902780] 러시아(RU) 2023년 → 0건

==================================================
▶ PET (390761) 신규 수집 시작
==================================================
  (111/260) [390761] 미국(US) 2019년 → 12건
  (112/260) [390761] 미국(US) 2020년 → 12건
  (113/260) [390761] 미국(US) 2021년 → 12건
  (114/260) [390761] 미국(US) 2022년 → 12건
  (115/260) [390761] 미국(US) 2023년 → 12건
  (116/260) [390761] 미국(US) 2024년 → 12건
  (117/260) [390761] 중국(CN) 2019년 → 12건
  (118/260) [390761] 중국(CN) 2020년 → 12건
  (119/260) [390761] 중국(CN) 2021년 → 12건
  (120/260) [390761] 중국(CN) 2022년 → 12건
  (121/260) [390761] 중국(CN) 2023년 → 12건
  (122/260) [390761] 중국(CN) 2024년 → 12건
  (123/260) [390761] 베트남(VN) 2019년 → 12건
  (124/260) [390761] 베트남(VN) 2020년 → 12건
  (125/260) [390761] 베트남(VN) 2021년 → 12건
  (126/260) [390761] 베트남(VN) 2022년 → 12건
  (127/260) [390761] 베트남(VN) 2023년 → 12건
  (128/260) [390761] 베트남(VN) 2024년 → 12건
  (129/260) [390761] 홍콩(HK) 2019년 → 12건
  (130/260) [390761] 홍콩(HK) 2020년 → 11건
  (131/260) [390761] 홍콩(HK) 2021년 → 12건
  (132/260) [390761] 홍콩(HK) 2022년 → 12건
  (133/260) [390761] 홍콩(HK) 2023년 → 12건
  (134/260) [390761] 홍콩(HK) 2024년 → 11건
  (135/260) [390761] 일본(JP) 2019년 → 12건
  (136/260) [390761] 일본(JP) 2020년 → 12건
  (137/260) [390761] 일본(JP) 2021년 → 12건
  (138/260) [390761] 일본(JP) 2022년 → 12건
  (139/260) [390761] 일본(JP) 2023년 → 12건
  (140/260) [390761] 일본(JP) 2024년 → 12건
  (141/260) [390761] 대만(TW) 2019년 → 12건
  (142/260) [390761] 대만(TW) 2020년 → 12건
  (143/260) [390761] 대만(TW) 2021년 → 12건
  (144/260) [390761] 대만(TW) 2022년 → 12건
  (145/260) [390761] 대만(TW) 2023년 → 12건
  (146/260) [390761] 대만(TW) 2024년 → 12건
  (147/260) [390761] 인도(IN) 2019년 → 12건
  (148/260) [390761] 인도(IN) 2020년 → 11건
  (149/260) [390761] 인도(IN) 2021년 → 12건
  (150/260) [390761] 인도(IN) 2022년 → 12건
  (151/260) [390761] 인도(IN) 2023년 → 12건
  (152/260) [390761] 인도(IN) 2024년 → 12건
  (153/260) [390761] 싱가포르(SG) 2019년 → 2건
  (154/260) [390761] 싱가포르(SG) 2020년 → 2건
  (155/260) [390761] 싱가포르(SG) 2021년 → 4건
  (156/260) [390761] 싱가포르(SG) 2022년 → 2건
  (157/260) [390761] 싱가포르(SG) 2023년 → 4건
  (158/260) [390761] 싱가포르(SG) 2024년 → 2건
  (159/260) [390761] 말레이시아(MY) 2019년 → 12건
  (160/260) [390761] 말레이시아(MY) 2020년 → 12건
  (161/260) [390761] 말레이시아(MY) 2021년 → 12건
  (162/260) [390761] 말레이시아(MY) 2022년 → 12건
  (163/260) [390761] 말레이시아(MY) 2023년 → 12건
  (164/260) [390761] 말레이시아(MY) 2024년 → 12건
  (165/260) [390761] 호주(AU) 2019년 → 8건
  (166/260) [390761] 호주(AU) 2020년 → 7건
  (167/260) [390761] 호주(AU) 2021년 → 9건
  (168/260) [390761] 호주(AU) 2022년 → 6건
  (169/260) [390761] 호주(AU) 2023년 → 7건
  (170/260) [390761] 호주(AU) 2024년 → 10건
  (171/260) [390761] 독일(DE) 2019년 → 12건
  (172/260) [390761] 독일(DE) 2020년 → 12건
  (173/260) [390761] 독일(DE) 2021년 → 12건
  (174/260) [390761] 독일(DE) 2022년 → 12건
  (175/260) [390761] 독일(DE) 2023년 → 11건
  (176/260) [390761] 독일(DE) 2024년 → 12건
  (177/260) [390761] 네덜란드(NL) 2019년 → 8건
  (178/260) [390761] 네덜란드(NL) 2020년 → 4건
  (179/260) [390761] 네덜란드(NL) 2021년 → 7건
  (180/260) [390761] 네덜란드(NL) 2022년 → 8건
  (181/260) [390761] 네덜란드(NL) 2023년 → 12건
  (182/260) [390761] 네덜란드(NL) 2024년 → 12건
  (183/260) [390761] 영국(GB) 2019년 → 8건
  (184/260) [390761] 영국(GB) 2020년 → 8건
  (185/260) [390761] 영국(GB) 2021년 → 3건
  (186/260) [390761] 영국(GB) 2022년 → 6건
  (187/260) [390761] 영국(GB) 2023년 → 9건
  (188/260) [390761] 영국(GB) 2024년 → 10건
  (189/260) [390761] 폴란드(PL) 2019년 → 11건
  (190/260) [390761] 폴란드(PL) 2020년 → 9건
  (191/260) [390761] 폴란드(PL) 2021년 → 10건
  (192/260) [390761] 폴란드(PL) 2022년 → 10건
  (193/260) [390761] 폴란드(PL) 2023년 → 11건
  (194/260) [390761] 폴란드(PL) 2024년 → 12건
  (195/260) [390761] 이탈리아(IT) 2019년 → 12건
  (196/260) [390761] 이탈리아(IT) 2020년 → 12건
  (197/260) [390761] 이탈리아(IT) 2021년 → 12건
  (198/260) [390761] 이탈리아(IT) 2022년 → 12건
  (199/260) [390761] 이탈리아(IT) 2023년 → 12건
  (200/260) [390761] 이탈리아(IT) 2024년 → 12건
  (201/260) [390761] 사우디(SA) 2019년 → 0건
  (202/260) [390761] 사우디(SA) 2020년 → 0건
  (203/260) [390761] 사우디(SA) 2021년 → 0건
  (204/260) [390761] 사우디(SA) 2022년 → 0건
  (205/260) [390761] 사우디(SA) 2023년 → 2건
  (206/260) [390761] 사우디(SA) 2024년 → 2건
  (207/260) [390761] UAE(AE) 2019년 → 3건
  (208/260) [390761] UAE(AE) 2020년 → 0건
  (209/260) [390761] UAE(AE) 2021년 → 5건
  (210/260) [390761] UAE(AE) 2022년 → 0건
  (211/260) [390761] UAE(AE) 2023년 → 2건
  (212/260) [390761] UAE(AE) 2024년 → 1건
  (213/260) [390761] 멕시코(MX) 2019년 → 12건
  (214/260) [390761] 멕시코(MX) 2020년 → 12건
  (215/260) [390761] 멕시코(MX) 2021년 → 12건
  (216/260) [390761] 멕시코(MX) 2022년 → 11건
  (217/260) [390761] 멕시코(MX) 2023년 → 7건
  (218/260) [390761] 멕시코(MX) 2024년 → 9건
  (219/260) [390761] 캐나다(CA) 2019년 → 9건
  (220/260) [390761] 캐나다(CA) 2020년 → 11건
  (221/260) [390761] 캐나다(CA) 2021년 → 4건
  (222/260) [390761] 캐나다(CA) 2022년 → 6건
  (223/260) [390761] 캐나다(CA) 2023년 → 9건
  (224/260) [390761] 캐나다(CA) 2024년 → 11건
  (225/260) [390761] 브라질(BR) 2019년 → 11건
  (226/260) [390761] 브라질(BR) 2020년 → 11건
  (227/260) [390761] 브라질(BR) 2021년 → 7건
  (228/260) [390761] 브라질(BR) 2022년 → 6건
  (229/260) [390761] 브라질(BR) 2023년 → 6건
  (230/260) [390761] 브라질(BR) 2024년 → 9건
  (231/260) [390761] 태국(TH) 2019년 → 12건
  (232/260) [390761] 태국(TH) 2020년 → 11건
  (233/260) [390761] 태국(TH) 2021년 → 12건
  (234/260) [390761] 태국(TH) 2022년 → 12건
  (235/260) [390761] 태국(TH) 2023년 → 12건
  (236/260) [390761] 태국(TH) 2024년 → 12건
  (237/260) [390761] 인도네시아(ID) 2019년 → 10건
  (238/260) [390761] 인도네시아(ID) 2020년 → 9건
  (239/260) [390761] 인도네시아(ID) 2021년 → 12건
  (240/260) [390761] 인도네시아(ID) 2022년 → 12건
  (241/260) [390761] 인도네시아(ID) 2023년 → 12건
  (242/260) [390761] 인도네시아(ID) 2024년 → 12건
  (243/260) [390761] 필리핀(PH) 2019년 → 11건
  (244/260) [390761] 필리핀(PH) 2020년 → 9건
  (245/260) [390761] 필리핀(PH) 2021년 → 8건
  (246/260) [390761] 필리핀(PH) 2022년 → 10건
  (247/260) [390761] 필리핀(PH) 2023년 → 12건
  (248/260) [390761] 필리핀(PH) 2024년 → 11건
  (249/260) [390761] 방글라데시(BD) 2019년 → 0건
  (250/260) [390761] 방글라데시(BD) 2020년 → 0건
  (251/260) [390761] 방글라데시(BD) 2021년 → 0건
  (252/260) [390761] 방글라데시(BD) 2022년 → 0건
  (253/260) [390761] 방글라데시(BD) 2023년 → 4건
  (254/260) [390761] 방글라데시(BD) 2024년 → 0건
  (255/260) [390761] 러시아(RU) 2019년 → 12건
  (256/260) [390761] 러시아(RU) 2020년 → 7건
  (257/260) [390761] 러시아(RU) 2021년 → 5건
  (258/260) [390761] 러시아(RU) 2022년 → 10건
  (259/260) [390761] 러시아(RU) 2023년 → 8건
  (260/260) [390761] 러시아(RU) 2024년 → 10건

재수집 결과 저장: trade_data_retry.csv (4,169행)

==================================================
기존 데이터와 병합 중...

기존 데이터:   184,661행
재수집 데이터: 4,169행
중복 제거:     125254행

==================================================
✅ 병합 완료: trade_data_merged.csv
   최종 행수: 63,576행

▶ HS코드별 행수 (상위 10개):
HS코드    품목명
271019  기타석유제품      1800
330499  화장품기타       1799
870899  기타자동차부품     1798
847989  일반기계기타      1796
300490  의약품기타       1796
390210  폴리프로필렌      1794
851762  통신기기부품      1778
903289  계측제어기기      1776
390120  폴리에틸렌고밀도    1750
390110  폴리에틸렌저밀도    1747

In [12]:
import pandas as pd
df = pd.read_csv("trade_data_final.csv", dtype=str)
print(df[["연월", "HS코드", "국가코드"]].head(20).to_string())
print("\n중복 행수:", df.duplicated(subset=["연월","HS코드","국가코드"]).sum())

         연월    HS코드 국가코드
0   2020-11  720826   AU
1   2020-12  720826   AU
2   2023-07  720826   AU
3   2023-10  720826   AU
4   2023-11  720826   AU
5   2023-12  720826   AU
6   2024-03  720826   AU
7   2024-05  720826   AU
8   2024-08  720826   AU
9   2024-12  720826   AU
10  2019-01  720826   BD
11  2019-10  720826   BD
12  2020-01  720826   BD
13  2020-02  720826   BD
14  2020-03  720826   BD
15  2020-03  720826   BD
16  2020-06  720826   BD
17  2020-07  720826   BD
18  2020-12  720826   BD
19  2021-02  720826   BD

중복 행수: 123272

In [13]:
import pandas as pd

# 1. 기존 파일 로드
df = pd.read_csv("trade_data_final.csv", dtype=str)
print(f"로드: {len(df):,}행")

# 2. 기존 데이터 내 중복 먼저 제거 (첫 번째 행 유지)
df = df.drop_duplicates(subset=["연월", "HS코드", "국가코드"], keep="first")
print(f"중복 제거 후: {len(df):,}행")

# 3. 390760 제거
df = df[df["HS코드"] != "390760"]
print(f"390760 제거 후: {len(df):,}행")

# 4. 재수집 데이터 로드 및 병합
retry = pd.read_csv("trade_data_retry.csv", dtype=str)
df_merged = pd.concat([df, retry], ignore_index=True)

# 5. 최종 중복 제거 (재수집 우선)
df_merged = df_merged.drop_duplicates(subset=["연월", "HS코드", "국가코드"], keep="last")
print(f"최종: {len(df_merged):,}행")

# 6. 저장
df_merged.to_csv("trade_data_merged.csv", index=False, encoding="utf-8-sig")
print("✅ 저장 완료")

로드: 184,661행
중복 제거 후: 61,389행
390760 제거 후: 61,389행
최종: 63,576행
✅ 저장 완료

In [16]:
# PET 확인
import pandas as pd
df = pd.read_csv("trade_data_merged.csv", dtype=str)
pet = df[df["HS코드"] == "390761"]
print(f"PET 행수: {len(pet)}")
print(pet.groupby("국가명")["연월"].count().to_string())

PET 행수: 1370
국가명
UAE      11
네덜란드     51
대만       72
독일       71
러시아      52
말레이시아    72
멕시코      63
미국       72
방글라데시     4
베트남      72
브라질      50
사우디       4
싱가포르     16
영국       44
이탈리아     72
인도       71
인도네시아    67
일본       72
중국       72
캐나다      50
태국       71
폴란드      63
필리핀      61
호주       47
홍콩       70

In [18]:
trade = pd.read_csv('./data/trade_data_merged.csv')
trade.head()

,연월,연도,월,HS코드,품목명,충격유형,국가코드,국가명,수출금액,수출중량,수입금액,수입중량,무역수지,날짜
0,2020-11,2020,11,720826,열연강판,금리,AU,호주,14624,24620,0,0,14624,2020-11-01
1,2020-12,2020,12,720826,열연강판,금리,AU,호주,14994,24620,0,0,14994,2020-12-01
2,2023-07,2023,7,720826,열연강판,금리,AU,호주,40084,46340,0,0,40084,2023-07-01
3,2023-10,2023,10,720826,열연강판,금리,AU,호주,33264,49500,0,0,33264,2023-10-01
4,2023-11,2023,11,720826,열연강판,금리,AU,호주,22098,29220,0,0,22098,2023-11-01

2. 외국인 투자유치(FDI) 동향

In [7]:
#fdi = pd.read_csv('산업별_외국인_투자_유치_실적_201501_202404.csv', encoding='ANSI', header=None)

#fdi.head()

# 전처리

- 날짜 컬럼 datetime 변환 & 일별 -> 월별 평균

In [36]:
# 각 데이터 날짜 형식 확인
for name, df in [("ex_rate", ex_rate), ("kr_rate", kr_rate),
                 ("us_rate", us_rate),("dubai", dubai)]:
    print(f"{name}: {df['날짜'].iloc[0]} / dtype: {df['날짜'].dtype}")

ex_rate: 2019-01-02 00:00:00 / dtype: datetime64[ns]
kr_rate: 2019-01-01 00:00:00 / dtype: datetime64[ns]
us_rate: 2019-01-01 / dtype: object
dubai: 2019-01-02 00:00:00 / dtype: datetime64[ns]

In [37]:
# 1. 모든 데이터 날짜 컬럼 datetime 변환
ex_rate["날짜"]  = pd.to_datetime(ex_rate["날짜"])                       
kr_rate["날짜"]  = pd.to_datetime(kr_rate["날짜"], format="%Y%m")       
us_rate["날짜"]  = pd.to_datetime(us_rate["날짜"])                      
dubai["날짜"]      = pd.to_datetime(dubai["날짜"], format="%y년%m월%d일")

In [38]:
# 2. 일별 -> 월별 평균
daily_cols = {"ex_rate": (ex_rate, "원/달러환율"), "dubai": (dubai, "Dubai")}

def to_monthly(df, cols):
    if isinstance(cols, list):
        return df.groupby(df["날짜"].dt.to_period("M"))[cols].mean().reset_index()
    return df.groupby(df["날짜"].dt.to_period("M"))[cols].mean().reset_index()

ex_rate_m = to_monthly(ex_rate, "원/달러환율")
dubai_m     = to_monthly(dubai, "Dubai")

# 월별 데이터도 Period로 통일
kr_rate["날짜"] = kr_rate["날짜"].dt.to_period("M")
us_rate["날짜"] = us_rate["날짜"].dt.to_period("M")

In [40]:
# 3. 병합
X_df = (ex_rate_m
         .merge(kr_rate,          on="날짜", how="left")
         .merge(us_rate,          on="날짜", how="left")
         .merge(dubai_m[["날짜", "Dubai"]], on="날짜", how="left"))

In [41]:
# 4. 분석 기간 필터링
X_df = X_df[
    (X_df["날짜"] >= pd.Period("2019-01", "M")) &
    (X_df["날짜"] <= pd.Period("2024-12", "M"))
].reset_index(drop=True)

print(X_df.shape)   # (72, 5)
print(X_df.head(5))
print(X_df.isnull().sum())  # 결측치 확인

(72, 5)
        날짜       원/달러환율  한국금리  미국금리      Dubai
0  2019-01  1122.000000  1.75  2.40  59.087273
1  2019-02  1122.447059  1.75  2.40  58.128500
2  2019-03  1130.720000  1.75  2.41  66.941905
3  2019-04  1140.950000  1.75  2.42  70.944762
4  2019-05  1183.290476  1.75  2.39  63.350435
날짜        0
원/달러환율    0
한국금리      0
미국금리      0
Dubai     0
dtype: int64

### 단위
- 원/달러 환율: 원(₩) ex. 1,122원
- 한국금리: %
- 미국금리: %
- 두바이유: 달러/배럴 ex. 59.09 달러

In [42]:
X_df.to_csv('독립변수.csv')

### FDI 데이터 Wide -> Long 변환

In [102]:
import numpy as np

# 분기·항목 컬럼명 조합
quarters = fdi.iloc[0, 2:].tolist()
items = fdi.iloc[1, 2:].tolist()

filled_q, last = [], ''
for q in quarters:
    if str(q) != 'nan' and q != last:
        last = q
    filled_q.append(last)

col_names = ['산업대분류', '산업소분류'] + [f'{q}_{it}' for q, it in zip(filled_q, items)]
data = fdi.iloc[2:].copy()
data.columns = col_names
data = data.reset_index(drop = True)

In [103]:
# Wide -> Long 변환
fdi_long = data.melt(id_vars=['산업대분류', '산업소분류'], var_name='분기_항목', value_name='값')
fdi_long['연도'] = fdi_long['분기_항목'].str.extract(r'(\d{4})')
fdi_long['분기'] = fdi_long['분기_항목'].str.extract(r'(\d)/4')
fdi_long['항목'] = fdi_long['분기_항목'].str.extract(r'_(.+)')
fdi_long = fdi_long.drop(columns='분기_항목')

# 신고금액만 추출, 소계 행만
fdi = (fdi_long[fdi_long['항목'] == '신고금액 (천불)']
       .drop(columns='항목')
       .rename(columns={'값': '신고금액(천불)'})
       .reset_index(drop=True))

fdi['신고금액(천불)'] = pd.to_numeric(fdi['신고금액(천불)'].replace('-', np.nan))

print(fdi.shape)
fdi.head(10)

(1320, 5)

       산업대분류     산업소분류   신고금액(천불)    연도 분기
0          계        소계  3554801.0  2015  1
1  농·축·수산·광업        소계      291.0  2015  1
2  농·축·수산·광업    농·축·임업      291.0  2015  1
3  농·축·수산·광업        어업        0.0  2015  1
4  농·축·수산·광업        광업        0.0  2015  1
5        제조업        소계   385270.0  2015  1
6        제조업        식품     2340.0  2015  1
7        제조업  섬유·직물·의류       95.0  2015  1
8        제조업     제지·목재     1677.0  2015  1
9        제조업        화공   101019.0  2015  1

In [104]:
print(fdi['산업대분류'].unique())
print(fdi['산업소분류'].unique())

<StringArray>
['계', '농·축·수산·광업', '제조업', '서비스업', '전기·가스·수도·환경정화·건설']
Length: 5, dtype: str
<StringArray>
[          '소계',       '농·축·임업',           '어업',           '광업',
           '식품',     '섬유·직물·의류',        '제지·목재',           '화공',
           '의약',     '비금속 광물제품',    '금속·금속가공제품',    '기계장비·의료정밀',
        '전기·전자',        '운송용기계',         '기타제조',     '도·소매(유통)',
       '숙박·음식점',        '운수·창고',         '정보통신',        '금융·보험',
          '부동산',      '사업지원·임대', '연구개발·전문·과학기술',    '여가·스포츠·오락',
     '공공·기타서비스',        '전기·가스',   '수도·하수·환경정화',         '종합건설',
      '전문직별 공사']
Length: 29, dtype: str

### 수출입 데이터

In [23]:
import pandas as pd

# ================================================
# STEP 1. 데이터 로드
# ================================================

df = pd.read_csv("./data/trade_data_merged.csv", dtype=str)
print(f"원본 행수: {len(df):,}")


# ================================================
# STEP 2. 매핑 테이블 정의
# ================================================

HS_INFO = {
    "854231": ("반도체_메모리",       "환율"),
    "854232": ("반도체_비메모리",     "환율"),
    "854239": ("기타집적회로",        "환율"),
    "851762": ("통신기기부품",        "환율"),
    "851769": ("기타통신기기",        "환율"),
    "852872": ("평판디스플레이",      "환율"),
    "870321": ("승용차_1000cc이하",   "환율"),
    "870322": ("승용차_1000~1500cc", "환율"),
    "870323": ("승용차_1500~3000cc", "환율"),
    "870324": ("승용차_3000cc초과",   "환율"),
    "870840": ("자동차변속기",        "환율"),
    "870850": ("자동차구동축",        "환율"),
    "870899": ("기타자동차부품",      "환율"),
    "901380": ("광학기기",            "환율"),
    "903289": ("계측제어기기",        "환율"),
    "271012": ("경유등유",            "유가"),
    "271019": ("기타석유제품",        "유가"),
    "271111": ("LPG액화",             "유가"),
    "271121": ("LNG액화",             "유가"),
    "290110": ("에틸렌",              "유가"),
    "290121": ("에틸렌기타",          "유가"),
    "290129": ("기타기초유분",        "유가"),
    "390110": ("폴리에틸렌저밀도",    "유가"),
    "390120": ("폴리에틸렌고밀도",    "유가"),
    "390210": ("폴리프로필렌",        "유가"),
    "390410": ("PVC",                 "유가"),
    "390761": ("PET",                 "유가"),
    "330499": ("화장품기타",          "유가"),
    "320419": ("합성염료",            "유가"),
    "381400": ("혼합용제희석제",      "유가"),
    "847989": ("일반기계기타",        "금리"),
    "847950": ("산업용로봇",          "금리"),
    "842951": ("불도저굴착기",        "금리"),
    "842952": ("스크레이퍼",          "금리"),
    "890190": ("선박기타",            "금리"),
    "890120": ("탱커",                "금리"),
    "890130": ("냉동선",              "금리"),
    "720826": ("열연강판",            "금리"),
    "720839": ("냉연강판",            "금리"),
    "730511": ("강관",                "금리"),
    "850760": ("리튬이온이차전지",    "복합"),
    "850780": ("기타이차전지",        "복합"),
    "848620": ("반도체제조장비",      "복합"),
    "848630": ("반도체공정장비",      "복합"),
    "300490": ("의약품기타",          "복합"),
    "300420": ("항생제",              "복합"),
    "880240": ("항공기",              "복합"),
    "880330": ("항공기부품",          "복합"),
    "854140": ("태양전지",            "복합"),
    "902780": ("분석기기",            "복합"),
}

COUNTRY_INFO = {
    "US": "미국",       "CN": "중국",       "VN": "베트남",
    "HK": "홍콩",       "JP": "일본",       "TW": "대만",
    "IN": "인도",       "SG": "싱가포르",   "MY": "말레이시아",
    "AU": "호주",       "DE": "독일",       "NL": "네덜란드",
    "GB": "영국",       "PL": "폴란드",     "IT": "이탈리아",
    "SA": "사우디",     "AE": "UAE",        "MX": "멕시코",
    "CA": "캐나다",     "BR": "브라질",     "TH": "태국",
    "ID": "인도네시아", "PH": "필리핀",     "BD": "방글라데시",
    "RU": "러시아",
}


# ================================================
# STEP 3. 날짜 컬럼 정리
# ================================================

# 날짜 → YYYY-MM Period 형식으로 변환
# 월별 평균 데이터라 월까지만 표시
df["날짜"] = pd.to_datetime(df["날짜"], format="%Y-%m-%d", errors="coerce").dt.to_period("M")

# 불필요한 날짜 컬럼 제거
df = df.drop(columns=["연월", "연도", "월"])

print(f"날짜 컬럼 정리 완료 (YYYY-MM 형식)")


# ================================================
# STEP 4. 숫자형 변환
# ================================================

num_cols = ["수출금액", "수출중량", "수입금액", "수입중량", "무역수지"]
for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

print(f"숫자형 변환 완료")


# ================================================
# STEP 5. 교역 없는 달 0으로 채우기
# ================================================
# 거시지표는 매월 있는데 수출 데이터가 띄엄띄엄 있으면
# 교차 분석 시 불일치 → 교역 없는 달은 0으로 채움

date_range = pd.period_range(
    start=df["날짜"].min(),
    end=df["날짜"].max(),
    freq="M"
)

hs_list      = list(HS_INFO.keys())
country_list = list(COUNTRY_INFO.keys())

print(f"\n0 채우기 시작...")
print(f"  기간: {date_range[0]} ~ {date_range[-1]} ({len(date_range)}개월)")
print(f"  HS코드: {len(hs_list)}개 × 국가: {len(country_list)}개")
print(f"  이론상 최대 행수: {len(date_range) * len(hs_list) * len(country_list):,}")

# 전체 조합 인덱스 생성
full_index = pd.MultiIndex.from_product(
    [date_range, hs_list, country_list],
    names=["날짜", "HS코드", "국가코드"]
)
df_full = pd.DataFrame(index=full_index).reset_index()

# 기존 데이터 병합
df_merged = df_full.merge(
    df[["날짜", "HS코드", "국가코드"] + num_cols],
    on=["날짜", "HS코드", "국가코드"],
    how="left"
)

# 수치 컬럼 0으로 채우기
for col in num_cols:
    df_merged[col] = df_merged[col].fillna(0)

print(f"  0 채우기 완료: {len(df_merged):,}행")


# ================================================
# STEP 6. 품목명·충격유형·국가명 채우기
# ================================================
# 0으로 채운 행은 join이 안 돼서 NaN → 매핑 딕셔너리로 직접 채움

df_merged["품목명"]  = df_merged["HS코드"].map(
    lambda x: HS_INFO.get(str(x), (None, None))[0]
)
df_merged["충격유형"] = df_merged["HS코드"].map(
    lambda x: HS_INFO.get(str(x), (None, None))[1]
)
df_merged["국가명"] = df_merged["국가코드"].map(COUNTRY_INFO)

# NaN 최종 확인
nan_check = df_merged[["품목명", "충격유형", "국가명"]].isnull().sum()
print(f"\nNaN 확인: {nan_check.to_dict()}")


# ================================================
# STEP 7. 정렬 및 저장
# ================================================

df_merged = df_merged.sort_values(
    ["충격유형", "HS코드", "국가코드", "날짜"]
).reset_index(drop=True)

# 컬럼 순서 정리
col_order = ["날짜", "HS코드", "품목명", "충격유형",
             "국가코드", "국가명",
             "수출금액", "수출중량", "수입금액", "수입중량", "무역수지"]
df_merged = df_merged[col_order]

df_merged.to_csv("trade_data_preprocessed.csv", index=False, encoding="utf-8-sig")

print(f"\n{'='*50}")
print(f"✅ 전처리 완료: trade_data_preprocessed.csv")
print(f"   최종 행수: {len(df_merged):,}")
print(f"\n▶ 컬럼 구성:")
for col in df_merged.columns:
    print(f"   {col}: {df_merged[col].dtype}")

print(f"\n▶ 샘플 (열연강판 × 호주 2019년 - 0 채우기 확인):")
sample = df_merged[
    (df_merged["HS코드"] == "720826") &
    (df_merged["국가코드"] == "AU") &
    (df_merged["날짜"].astype(str).str.startswith("2019"))
]
print(sample[["날짜", "수출금액", "수입금액"]].to_string(index=False))

원본 행수: 63,576
날짜 컬럼 정리 완료 (YYYY-MM 형식)
숫자형 변환 완료

0 채우기 시작...
  기간: 2019-01 ~ 2024-12 (72개월)
  HS코드: 50개 × 국가: 25개
  이론상 최대 행수: 90,000
  0 채우기 완료: 90,000행

NaN 확인: {'품목명': 0, '충격유형': 0, '국가명': 0}

==================================================
✅ 전처리 완료: trade_data_preprocessed.csv
   최종 행수: 90,000

▶ 컬럼 구성:
   날짜: period[M]
   HS코드: object
   품목명: object
   충격유형: object
   국가코드: object
   국가명: object
   수출금액: float64
   수출중량: float64
   수입금액: float64
   수입중량: float64
   무역수지: float64

▶ 샘플 (열연강판 × 호주 2019년 - 0 채우기 확인):
     날짜  수출금액  수입금액
2019-01   0.0   0.0
2019-02   0.0   0.0
2019-03   0.0   0.0
2019-04   0.0   0.0
2019-05   0.0   0.0
2019-06   0.0   0.0
2019-07   0.0   0.0
2019-08   0.0   0.0
2019-09   0.0   0.0
2019-10   0.0   0.0
2019-11   0.0   0.0
2019-12   0.0   0.0